### ISSUE TITLE
block reindent feature

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#1002]
This would be follow-up to #971; it would be nice if we had the ability to recalculate the indentation of a series of lines, based on context.

This would need to also be implemented in the syntect plugin, likely as a custom command such as with comment toggling, in #991.

The basic algorithm for this is pretty straight forward; we take the indentation of the previous line as the reference, and then for each line to be adjusted we check for increase/decrease and then update the whitespace as needed, similarly to how we currently do when adjusting indentation during editing.

**Comment by tzvipm** [comment]
@cmyr would this perhaps better fall under a more generic `reformat` command that would communicate with a language service? I'm thinking this sounds a lot like `rustfmt` / `prettier` only a bit more simplistic.

**Comment by cmyr** [comment]
@tzvipm I think these are separate but related. This is specifically about running the existing indent rules against a batch of lines, but not doing any fancy formatting; it would be more general purpose. Those other tools definitely have their place as well (and where they exist they may make this irrelevant) but I still think this is a useful independent feature.

**Comment by scholtzan** [comment]
I think this should do it: https://github.com/xi-editor/xi-editor/pull/1057
