### ISSUE TITLE
match indentation level on paste

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#1004]
Another self-contained bit of followup to #991: it would be nice if (as an option? as a default behaviour?) we would match the indentation of pasted text to appropriate level for the paste location.

I think this can be as simple as computing the 'delta whitespace' for the first pasted line, and then adjusting each subsequent line by the same amount; that is, we assume that the pasted block is formatted correctly relative to itself, and we just adjust it relative to the destination.

This _may_ require a new `Paste` `EditType`; currently paste is part of `Other`. I would try it first with `Other`, though, and see if that worked correctly.

**Comment by cmyr** [comment]
yes, sorry if that was unclear; there would only be a single delta, 'delta whitespace' is probably a confusing term. I just mean the difference in 'whitespace units' between the source and the destination.

**Comment by scholtzan** [comment]
Fixed (or added) in https://github.com/xi-editor/xi-editor/pull/1040
