### ISSUE TITLE
Deprecate `CancelOperation`, add `CollapseSelection` and `UnsetFind` RPCs

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#1015]
Currently `CancelOperation` is a general purpose RPC that corresponds to the user pressing <kbd>esc</kbd>. This is tricky, because the correct behaviour is very dependent on other state, such as the presence of find highlights etc.

I think that this should be replaced with specific commands for specific pieces of behaviour. The first two obvious ones would be `UnsetFind`, and `CollapseSelection`. (@scholtzan might have a better idea whether `UnsetFind` is necessary; there might be another option?

**Comment by scholtzan** [comment]
I was wondering what the behaviour of `UnsetFind` actually should be. Is it just that the search string gets deleted or should additionally all settings (regex, case-sensitvity, ...) get reset? `CancelOperation` is currently doing the latter. 
Usually, <kbd>esc</kbd> in combination with find seems to only hide the search bar. But maybe having `UnsetFind` might be useful in some context.

**Comment by cmyr** [comment]
I think we probably want to persist those other settings in general, and mostly just clear the highlights and the active search string? I think we should just try to match the behaviour of existing editors at this point. If I were implementing I would just go and look at existing editors and try to match whatever felt best. 🤷‍♂️

**Comment by scholtzan** [comment]
Okay, in this case I think we won't need `UnsetFind`. The behaviour can easily reproduced with the existing `find` or `multi_find` RPCs for which we'd just remove the search strings.

**Comment by cmyr** [comment]
Okay great, I wasn't sure how that worked.
