### ISSUE TITLE
Make `get_line_range` in view return `RangeInclusive` instead of `Range`

### ISSUE THREAD

**Issue by scholtzan** [xi-editor/xi-editor#1035]
Rust 2018 adds support for [inclusive ranges](https://rust-lang-nursery.github.io/edition-guide/rust-2018/data-types/inclusive-ranges.html). Currently, [`get_line_range` returns `Range`](https://github.com/xi-editor/xi-editor/blob/eeefad4fd6fb357f0e99c6c0cd78cb73e1a17617/rust/core-lib/src/view.rs#L1120), however it should be possible to change this to `RangeInclusive`. Changing this would also allow us to remove the clippy `#![allow(clippy::range_plus_one)]`.

**Comment by fominok** [comment]
Tried to return `RangeInclusive`, but `ExactSizeIterator<usize>` is not implemented for it, while on `editor.rs:474` it is required for a `.len()` method.

**Comment by cmyr** [comment]
@fominok hm, okay cool, thanks for looking into this!
