### ISSUE TITLE
run_all_checks failing on master

### ISSUE THREAD

**Issue by tzvipm** [xi-editor/xi-editor#1036]
# Xi-Editor Issue Template
- [x] I have searched existing issues and could not find my issue.
- [x] I have studied the documentation.

## Expected vs Actual

Expected `xi-editor/rust/run_all_checks` to exit with `0` status.

Actual: errors via `rustfmt` and `clippy` prevent test suite from running (unit test pass with `cargo test --all`)
```diff
$ xi-editor/rust/run_all_checks
      clippy 0.0.212 (29bf75cd 2018-12-05)
rustfmt 1.0.0-nightly (43206f41 2018-11-30)
Running rustfmt:
Diff in /Users/hartleymelamed/src/github.com/tzvipm/xi-editor/rust/core-lib/src/rpc.rs at line 568:
             Some(_) => {
                 return Err(de::Error::custom(
                     "'params' field, if present, must be object or array.",
-                ))
+                ));
             }
             None => false,
         };

Rustfmt failed. Please run rustfmt.
```

**Comment by tzvipm** [comment]
looks like the fix is to simply:
1. run `rustfmt` on the file mentioned
2. apply https://rust-lang.github.io/rust-clippy/master/index.html#deprecated_cfg_attr via global find/replace

PR coming up shortly

**Comment by tzvipm** [comment]
@cmyr, it prompted me to download the nightly versions of rustfmt and clippy when they weren’t installed initially. I was trying to downgrade to the stable versions, but couldn’t figure out how.

**Comment by cmyr** [comment]
Want to ping me on zulip when you have a chance and we can walk through this together?

**Comment by tzvipm** [comment]
Turns out the issues I encountered were due to me using nightly rust. The script works as expected on the stable channel.
