### ISSUE TITLE
Performance metrics and regression tracking

### ISSUE THREAD

**Issue by tzvipm** [xi-editor/xi-editor#1039]
From the October 2018 Roadmap in #937:

> At some point we will want to start more aggressively measuring and tracking performance. This is a vague, open-ended problem; but ideally we would have something like a CI system for performance, that would let us run some set of real-world benchmarks against new commits, and allow us to visualize changes over time. A good first step for this would be to create a new xi-bench crate that starts putting together these sorts of real-world benchmarks.

**Comment by tzvipm** [comment]
From the README:

> Incredibly high performance. All editing operations should commit and paint in under 16ms. The editor should never make you wait for anything.

**Comment by jansol** [comment]
What are you trying to say?

**Comment by tzvipm** [comment]
Sorry, @jansol, I am trying to say that I'd like to take a stab at some performance benchmarks. Unfortunately, there wasn't any issue for that, so I made one.

**Comment by jansol** [comment]
Yes.

**Comment by cmyr** [comment]
@tzvipm I think this is a great project, and am happy to chat about it!
