### ISSUE TITLE
Cursor should not return `Some` at end of tree if not a boundary?

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#1050]
Although it is [documented](https://github.com/xi-editor/xi-editor/blob/master/rust/rope/src/tree.rs#L632), I think the current behaviour is unexpected and likely to cause bugs.

`next` takes a metric; it seems reasonable to me that the EOF case is handled by checking whether EOF is a boundary in the given metric.

cc @raphlinus

**Comment by jansol** [comment]
Seems like a custom enum could make sense there. Say,
```rust
enum {
    Break(usize),
    Eof(usize)
}
```

**Comment by cmyr** [comment]
I think the way the cursor API is presented (`next` is specific to a given metric) means it makes sense to only include results that are boundaries in that metric.
