### ISSUE TITLE
Collect code coverage statistics

### ISSUE THREAD

**Issue by euclio** [xi-editor/xi-editor#1069]
# Xi-Editor Issue Template
- [x] I have searched existing issues and could not find my issue.
- [x] I have studied the documentation.

It would be nice to collect code coverage statistics for the project and upload them to codecov, so we could see where we're lacking in code coverage. I don't have access to my Linux box right now so I can't test how good the reporting is, but https://github.com/xd009642/tarpaulin looks promising.

**Comment by cmyr** [comment]
Yea, I think this would be a useful addition; if you're interested in trying to get this working let me know if there's any admin-ing I need to do.
