### ISSUE TITLE
xi-syntect-plugin: incorrect `exec_path` on windows

### ISSUE THREAD

**Issue by acheronfail** [xi-editor/xi-editor#1074]
When building `xi-core` and `xi-syntect-plugin` on Windows, `xi-core` cannot find the `xi-syntect-plugin` and generates a File Not Found error.

I believe the cause is because of this generated manifest: https://github.com/xi-editor/xi-editor/blob/c8dbc7bde3354b2432918d643dc1ba70e57abc0b/rust/syntect-plugin/manifest.toml#L4

This fixes it and everything works:

```diff
diff --git a/rust/syntect-plugin/manifest.toml b/rust/syntect-plugin/manifest.toml
index a72f065..414fc1e 100644
--- a/rust/syntect-plugin/manifest.toml
+++ b/rust/syntect-plugin/manifest.toml
@@ -1,7 +1,7 @@
 name = "xi-syntect-plugin"
 version = "0.0.0"
 scope = "global"
-exec_path = "./bin/xi-syntect-plugin"
+exec_path = "./bin/xi-syntect-plugin.exe"
 activations = ["autorun"]
 commands = []
```

---

Could we perhaps generate the manifest each time the plugin is built and use something like this to ensure the `exec_path` is correct per platform?

```diff
diff --git a/rust/syntect-plugin/examples/make_manifest.rs b/rust/syntect-plugin/examples/make_manifest.rs
index 45a6332..1c3746f 100644
--- a/rust/syntect-plugin/examples/make_manifest.rs
+++ b/rust/syntect-plugin/examples/make_manifest.rs
@@ -50,7 +50,11 @@ fn main() -> Result<(), io::Error> {
         .collect::<Vec<_>>();

     let (name, version) = parse_name_and_version()?;
-    let exec_path = PathBuf::from(format!("./bin/{}", &name));
+    let exec_path = if cfg!(windows) {
+        PathBuf::from(format!("./bin/{}.exe", &name))
+    } else {
+        PathBuf::from(format!("./bin/{}", &name))
+    };

     let mani = PluginDescription {
         name,
```

Right now the `make_manifest.rs` file isn't called at all (I believe the current setup is to run it locally and stage the result - see this commit: https://github.com/xi-editor/xi-editor/commit/8c5c636fdaab0e53e98a358bc37b598cce347d6f). Perhaps moving it into a `build.rs` might be beneficial.

**Comment by cmyr** [comment]
@acheronfail Maybe another solution would be to append `.exe` to all plugin paths when we're on windows? We should be able to do this when loading the manifest without much main.

We _could_ put this in `make_manifest.rs`, but that would only work for syntect; we'll need something that works for all plugins.

**Comment by acheronfail** [comment]
Would something as simple as this suffice? I didn't spend a lot of time going through the code, so I'm not sure if this is the right/only place:

```diff
diff --git a/rust/core-lib/src/plugins/mod.rs b/rust/core-lib/src/plugins/mod.rs
index 4154354..e4658a2 100644
--- a/rust/core-lib/src/plugins/mod.rs
+++ b/rust/core-lib/src/plugins/mod.rs
@@ -136,7 +136,14 @@ pub(crate) fn start_plugin_process(plugin_desc: Arc<PluginDescription>,
         .name(format!("<{}> core host thread", &plugin_desc.name))
         .spawn(move || {
             eprintln!("starting plugin {}", &plugin_desc.name);
-            let child = ProcCommand::new(&plugin_desc.exec_path)
+
+            let exec_path = if cfg!(windows) {
+                plugin_desc.exec_path.with_extension("exe")
+            } else {
+                plugin_desc.exec_path.clone()
+            };
+
+            let child = ProcCommand::new(&exec_path)
                 .stdin(Stdio::piped())
                 .stdout(Stdio::piped())
                 .spawn();
```

**Comment by cmyr** [comment]
Yea, this would work. And you could avoid the extra clone with something like,

```rust
let child = if cfg!(windows) {
    ProcCommand::new(plugin_desc.exec_path.with_extension("exe"))
} else {
    ProcCommand::new(&exec_path)
};
let child = child.stdin(Stdio::piped())
    .stdout(Stdio::piped())
    .spawn();
```

Although realistically a clone here is not a big issue.

In any case if you wanted to submit that patch we'd be happy to merge it?

**Comment by cmyr** [comment]
Oh: the 'right' way to do this, I think, would be a custom deserializer fn on that field, e.g. something like an annotation `#[serde(deserialize_with = "platform_exec_path")]` on the `exec_path` field of `PluginDescription`. This isn't quite as straight forward, though, so I think your solution is fine.

**Comment by acheronfail** [comment]
Good idea about using a custom deserialiser. 
I’ll make a PR shortly that closes this issue.  👍
