### ISSUE TITLE
LineSelect for wrapped lines

### ISSUE THREAD

**Issue by scholtzan** [xi-editor/xi-editor#1078]
When tripple-clicking on a wrapped line for me the expected behaviour would be that the entire logical line gets selected. Right now only the screen line gets selected.

**Comment by sjoshid** [comment]
@scholtzan Not sure what progress you have made here and if you are ok..I would like to take this up.

**Comment by scholtzan** [comment]
I haven't had time to work on this. So you can go ahead :)

**Comment by sjoshid** [comment]
@scholtzan Can you give the PR a try?
