### ISSUE TITLE
[RFC] Reporting xi-editor version

### ISSUE THREAD

**Issue by Cogitri** [xi-editor/xi-editor#1087]
# Xi-Editor Issue Template
- [X] I have searched existing issues and could not find my issue.
- [X] I have studied the documentation.

## Details

As discussed in #xi over on zulipchat, xi-editor should have some version reporting mechanism, e.g. to avoid incompatibilities (one can encounter _very_ weird bugs if the syntect plugin and xi were built from different revisions).

## Implementation

This could be handled as a notification which is sent to the frontend after `client_started`. It could look a little like this:

```
{"method": "version_string", "params": "0.0.x-<git-revision>"}
```

This could be done via a `build.rs`, I guess

**Comment by cmyr** [comment]
Thinking about this, i'm not sure it makes sense for this to be an RPC, although it isn't crazy. I can think of at least two other options, though: we could either just always log the current version at startup, or we could add a `--version` argument to the binary, where it would just print it's version and exit.

Both of these would do what we want, I think, which is give us another little tool for debugging.

**Comment by Cogitri** [comment]
I'd rather opt for always logging the the current version during startup then. GXI doesn't call an xi executable but rather uses the xi-core-lib, so a `--version` argument wouldn't work for it.

**Comment by cmyr** [comment]
interesting. Are you using the gtk runloop, or are you using xi-rpc?

**Comment by Cogitri** [comment]
I'm using xi-rpc.

**Comment by Cogitri** [comment]
As we've discussed on Zulip some tome ago this isn't really something we want - frontends should know what version of Xi they use (e.g. by vendoring it).
