### ISSUE TITLE
Crash when deleting backwards?

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#1089]
Just saw this on a recent build in what felt like a very innocuous situation, e.g. all ascii/latin-1, small file. 

```
thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', core-lib/src/backspace.rs:36:23
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: xi_core_lib::backspace::offset_for_delete_backwards
  10: xi_core_lib::editor::Editor::do_edit
  11: xi_core_lib::event_context::EventContext::dispatch_event
  12: xi_core_lib::event_context::EventContext::do_edit
  13: xi_core_lib::tabs::CoreState::client_notification
  14: <xi_core_lib::core::XiCore as xi_rpc::Handler>::handle_notification
  15: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
  18: crossbeam_utils::thread::scope
  19: <xi_rpc::RpcLoop<W>>::mainloop
  20: xi_core::main
  21: std::rt::lang_start::{{closure}}
  22: std::panicking::try::do_call
  23: __rust_maybe_catch_panic
  24: std::rt::lang_start_internal
  25: main
[2019-01-17][13:36:31][xi_rpc][ERROR] panic guard hit, closing runloop
```

**Comment by scholtzan** [comment]
This should fix it https://github.com/xi-editor/xi-editor/pull/1090?

**Comment by cmyr** [comment]
This is interesting, really tab_size == 0 should not be legal. I guess what's happened here is that the tab detection has failed, somehow? That's one problem, but I'm not sure what we want to do if the user explicitly sets 0 as the tab size. One possibility is that we delete their home directory and and change their username to the 😡 emoji?

**Comment by scholtzan** [comment]
That would be one way to make the user happy ;) 
Another option I was thinking about is showing an error popup similar to when a user tries to set a negative value. Or to check for `tab_size == 0` and handle these cases separately which is basically what https://github.com/xi-editor/xi-editor/pull/1090 does.

**Comment by cmyr** [comment]
yea, so i'm wondering if we can just say that the minimum valid value for tab_size is.. 1? 2? I'm not sure 1 really makes sense.

**Comment by scholtzan** [comment]
I would say 1, there might be cases where users want that.

**Comment by cmyr** [comment]
Okay, so how we'll want to do this is in config.rs, we do 'validation' just by trying to deserialize to our `BufferItems` struct. So we will need a custom [deserialize_with](https://serde.rs/field-attrs.html#deserialize_with) fn for the `tab_size` member, which returns an error if it's 0.

We'll also want to make sure that the autodetect whitespace fn can never return 0.

**Comment by scholtzan** [comment]
Sounds good. I can look into this in a bit.

**Comment by scholtzan** [comment]
Fixed in https://github.com/xi-editor/xi-editor/pull/1099
