### ISSUE TITLE
'new_view' creates the file specified by 'file_path'

### ISSUE THREAD

**Issue by Cogitri** [xi-editor/xi-editor#1092]
# Xi-Editor Issue Template
- [X] I have searched existing issues and could not find my issue.
- [X] I have studied the documentation.

## Details

using xi-editor rev 97a60f6f6591931877e0b48c8df0340b142616cd

### Expected

```
{"id"=0, "method": new_view, "params":{"file_path":"/tmp/file"}}
```

xi-editor creates a new view but only creates `/tmp/file`  after `save` has been called for that view.

### Actual

```
{"id"=0, "method": new_view, "params":{"file_path":"/tmp/file"}}
```

xi-editor creates an empty file `/tmp/file` upon creating the new view. This is irritating for users, as they might end up with empty files if they typo in the file name etc. even though they've never called save.

**Comment by cmyr** [comment]
I agree, i've encountered this as well and I don't think it's the correct behaviour.
