### ISSUE TITLE
Invalid config values are saved

### ISSUE THREAD

**Issue by scholtzan** [xi-editor/xi-editor#1094]
If an invalid config value, in `preferences.xiconfig`, for example `wrap_width = -2,` gets entered then an error popup will be shown but the value is saved. Should this be prevented?

**Comment by cmyr** [comment]
We don't have a good mechanism for this, right now; the config file is just a file, and we need the save to happen for us to know we should reload the config. (I assume you figured this out, but just for the record 👍)
