### ISSUE TITLE
Syntax detection fails for git commit messages

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#1096]
As of #1085 we now have syntax support for git commit messages; however we do not correctly guess the syntax of commits.

This is a simple fix: these files have names like `COMMIT_EDITMSG`, with no extension. When guessing a syntax for a file, we check for a file extension, and compare that to a list of known file extensions. We should change this so that if a file name does not have an extension, we just use the file name itself.

This should be a one or two line change in `core-lib/src/syntax.rs`. We should also be able to add a test to that file as well.

**Comment by kanishkarj** [comment]
I shall look into it.
