### ISSUE TITLE
i686 build broken

### ISSUE THREAD

**Issue by Cogitri** [xi-editor/xi-editor#1097]
Hello,

I've just updated xi-editor for my application and it seems like the build on i686 is broken:

https://travis-ci.org/void-linux/void-packages/jobs/483135656

Run on VoidLinux i686.

**Comment by cmyr** [comment]
ah interesting, it seems that whatever hardware they're running this on has avx2 instruction support without being x86_64? I didn't think this was a possible combination, but perhaps they're running under emulation or something.

In any case, there is an oversight here; these functions are only available on x86_64, but we don't actually check that before calling. Can patch shortly.

**Comment by Cogitri** [comment]
Thank you :)
