### ISSUE TITLE
Add support for TOML syntax, use for .xiconfig files

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#1104]
We do not currently ship with toml syntax, but this is something we can now address. This will involve a pr to https://github.com/xi-editor/syntect-resources to add a TOML package; then we will need to regenerate the data files in the syntect plugin.

To make this work with `.xiconfig` files, we will need to manually add `xiconfig` to the list of file extensions associated with the toml syntax when we generate the manifest. This will require a special case in `generate_manifest.rs`; while iterating through the languages, if the language is toml, we need to manually add the new file extension before writing the manifest file.

**Comment by jansol** [comment]
Closed by #1105
