### ISSUE TITLE
If saving to an existing file, keep the permissions

### ISSUE THREAD

**Issue by Cogitri** [xi-editor/xi-editor#1109]
af02680d739311a6ec09904cba9b3d5edfbc6b25 has introduced atomic saving, but this has broken file permission keeping. This is rather annoying when editing executables.

# Expected behavior:

```
touch new
chmod 755 new
gxi new # <-- save here
ls -lah new
```
returns: 
-rwxr-xr-x 1 rasmus rasmus 1 Feb  6 22:21 new

# Actual behavior

```
touch new
chmod 755 new
gxi new # <-- save here
ls -lah new
```

-rw-r--r-- 1 rasmus rasmus 1 Feb  6 22:21 new

**Comment by cmyr** [comment]
Additionally, it would be nice to also keep relevant file metadata, such as the original creation timestamp.

**Comment by Cogitri** [comment]
Heh, good timing, just created the PR to keep existing file perms. I guess on Windows there's nothing to keep since https://doc.rust-lang.org/std/fs/struct.Permissions.html only lists readonly as possible perm and we can't save to a readonly file anyway?

**Comment by cmyr** [comment]
Yes, it makes sense that doing this correctly will require taking platform specific code paths.

**Comment by jansol** [comment]
As far as I can tell what we should do is basically grab the output of `fstat()` and copy it as-is to the new file?

**Comment by Cogitri** [comment]
Well, that but in Rust, I guess

**Comment by cmyr** [comment]
Yea, I don't have a strong opinion on the exact approach.

**Comment by Cogitri** [comment]
I guess I'll just clamp the additional stuff onto file::FileInfo, it isn't much effort to do that

**Comment by jansol** [comment]
No shame in having platform-specific code paths for this.

**Comment by Cogitri** [comment]
Yup, we'll have to do that for std::os::unix::fs::PermissionsExt anyway

**Comment by Cogitri** [comment]
Alright, seems like Rust doesn't have a way to to set file times in the standard library yet. We could either implement something like it in xi, or add something like https://crates.io/filetime (conditionally?) to xi's deps.

**Comment by cmyr** [comment]
I'm happy to take on that dep.

**Comment by Cogitri** [comment]
Alright, want me to feature-ize that?

**Comment by Cogitri** [comment]
Alright, I haven't feature-ized it for now since it's not a big dep. Please take a look at the PR :)
