### ISSUE TITLE
Panics when sending RPC too early (?)

### ISSUE THREAD

**Issue by Cogitri** [xi-editor/xi-editor#1115]
## Details

- Tested on Linux
- Using Rustc 1.32.0, installed via rustup
- Tested in gxi frontend master

I've just added more threading to gxi's SharedQueue (which holds rpc from xi-editor until gxi handles it) in https://github.com/Cogitri/gxi/commit/dd8a00559509596d1d80ead20e9171cd34c5363f. This causes xi-editor to panic in non-release mode on big files due to https://github.com/xi-editor/xi-editor/blob/master/rust/core-lib/src/linewrap.rs#L676, I guess it doesn't like receiving some RPC before it has finished loading the file? Letting the thread sleep for ~100 msec fixes it, so I guess this is some timing problem.

See https://gist.github.com/Cogitri/c8f29a4b3a37530c88cb702277e71756 for the backtrace (and gxi logging).

**Comment by cmyr** [comment]
hmm, I'm confused as to what's going on here.

File loading is currently synchronous, and happens on the 'main thread', which also processes RPCs sequentially. So the file should be loaded before any RPC is handled?

Looking at the log, some things that stand out:

https://gist.github.com/Cogitri/c8f29a4b3a37530c88cb702277e71756#file-stacktrace-L27 – this seems weird? Maybe the response from the server is being interpreted as a request?
https://gist.github.com/Cogitri/c8f29a4b3a37530c88cb702277e71756#file-stacktrace-L51 – I would consider `request_lines` soft deprecated; if you tell us the scroll region we will always send you the correct lines. The one possible case for `request_lines` is prefetching during scrolling, but I'm not sure if this is done anywhere.


Can you describe in a bit more detail what your threads are doing?

**Comment by Cogitri** [comment]
I have a SharedQueue (under the hood it's crossbeam_deque::Dequeue) which holds CoreMsgs (stuff I've received from xi) so I can consume it later in the main thread. See https://github.com/Cogitri/gxi/blob/master/src/rpc.rs#L60 for how I add msgs to the queue. I then grab CoreMsgs in my main thread to process them in the frontend, see https://github.com/Cogitri/gxi/blob/master/src/main_win.rs#L91. Before I've used gtk::add_idle, which only executes actions when the gtk thread is idle (as the name suggest), which could lead to freezes (when gtk was busy doing drawing etc. but I needed to answer a request of xi), so I've moved that into its own thread.

> The one possible case for request_lines is prefetching during scrolling, but I'm not sure if this is done anywhere.

Thanks for the info about request_lines. Right now I use it to populate my own LineCache, but I'll switch to just using scroll then.

**Comment by cmyr** [comment]
Okay, I think the issue here is that you need to send `resize` before interacting with the view.

At some point we will change some of this view geometry stuff so that you init a view with a size, and then scrolling is just setting the size + offset, and we will do the math to determine what lines are visible.

Anyway, pardon the mess at the moment.

**Comment by Cogitri** [comment]
Alright. I've just added a sleep to the thread (ew), but I guess gxi's SharedQueue needs some restructuring to work without that, I can't initialize a new view without it, so I can't wait with initializing the thread until I can send resize to xi. I guess we can just leave this open.

**Comment by cmyr** [comment]
I'm a bit confused. It should be easy enough to just send resize immediately when you get the view_id back?

**Comment by Cogitri** [comment]
You mean I should just send a fake resize back?

**Comment by cmyr** [comment]
that would work; and depending on when and how you actually setup the frontend view you can probably know the size already?

**Comment by Cogitri** [comment]
Hum, I think GTK+ apps usually do set an initial size, but I'm not quite sure if that works so well with scaling.

**Comment by Cogitri** [comment]
> https://gist.github.com/Cogitri/c8f29a4b3a37530c88cb702277e71756#file-stacktrace-L51 – I would consider `request_lines` soft deprecated; if you tell us the scroll region we will always send you the correct lines. The one possible case for `request_lines` is prefetching during scrolling, but I'm not sure if this is done anywhere.

I've just fixed that (luckily that was an easy fix, thanks for making 'scroll_to' work well :), thank you very much for the info!
