### ISSUE TITLE
[Question][xi-rope] peek next char from cursor

### ISSUE THREAD

**Issue by ngortheone** [xi-editor/xi-editor#1120]
Hi everyone!

I am working on a parser lib and I use xi-rope as underlying data structure.
I need to be able to peek the next char, without advancing the cursor position. How can I do that?

For example - the code below is broken, because it is supposed to skip only whitespace, but it also consumes one extra char.

```rust

fn skip_whitespace(cursor: & mut Cursor<RopeInfo>) -> usize {
    let mut i: usize = 0;
    while let Some(c) = cursor.next_codepoint() {
        if !(c.is_whitespace()) {
            break
        } else {
            i+=1;
        }
    }
    return i;
}
...
#[test]
fn skip_whitespaces() {
    let r = Rope::from("  hello ");
    let mut cursor = Cursor::new(&r, 0);
    let spaces = skip_whitespace(&mut cursor);
    assert_eq!(spaces, 2);
}
```

I can rewind the cursor one char back, but I want to avoid that for efficiency sake.
I found that there is a way to get iterator over boundaries, but I don't know how to read chars from it.

Please help

**Comment by cmyr** [comment]
I've added this in https://github.com/xi-editor/xi-editor/pull/1123, let me know if that gives you what you need?

**Comment by ngortheone** [comment]
@cmyr this is great! Thanks!
