### ISSUE TITLE
Syntax highlighting only for visible range

### ISSUE THREAD

**Issue by scholtzan** [xi-editor/xi-editor#1130]
Only the first visible range in a document gets syntax highlighted:

<img width="945" alt="Screenshot 2019-03-09 at 7 10 22 PM" src="https://user-images.githubusercontent.com/1239705/54080193-68620b80-429f-11e9-8fb1-dfa242116284.png">

**Comment by cmyr** [comment]
Interesting, this seems to be a result of #1122 / 9b97df8. Will take a look, we were probably doing something that depended on the previous behaviour.
