### ISSUE TITLE
Cutting/Copying and Word Wrap doesn't work together nicely

### ISSUE THREAD

**Issue by Cogitri** [xi-editor/xi-editor#1138]
Hello,

It appears that Xi doesn't like me enabling word wrapping and then cutting/copying text in gxi, which ends in a deadlock (although that might very well be on gxi).

So when I cut I call the following code:

https://github.com/Cogitri/gxi/blob/master/src/rpc.rs#L429

Which sends the 'cut' edit_msg to Xi and waits until it sends back the String I'm cutting, so I can add it to the clipboard.

However, Xi sends me 'measure_width' after I've sent it the 'cut' edit_msg, so we both wait at each other, gxi waiting for the 'cut' output to be sent to it and Xi waiting for the output of 'measure_width' being returned to it. I'm not exactly sure if I can do something about that on gxi's side since I can't exactly not block on waiting for the cut output and timing out seems bad too.

**Comment by Cogitri** [comment]
Alrighty, nevermind, I can totally make that nonblocking in gxi (took me a recreational hike :P)

I am curious as to why this is blocking in Xi-editor though? Is this something that is being worked on, or can I help?

**Comment by cmyr** [comment]
@Cogitri there are plans to revamp how the word wrap stuff works, which will remove `measure_width`. The fix you've figured out (make the `cut` call non-blocking) would be my suggestion for the time being.

**Comment by Cogitri** [comment]
Alrighty then, works for now, thanks for the info :)
