### ISSUE TITLE
Displaying spaces, tabs (and other usually not drawn characters?)

### ISSUE THREAD

**Issue by Cogitri** [xi-editor/xi-editor#1144]
It would be really nice if Xi supported drawing tabs, spaces etc. I've (sort of) implemeted support for this in gxi by replacings spaces with a dot during rendering, but this comes with some problems (namely that I have to carefully space them to not mess up the cursor position and that theming them doesn't work properly because they're wider than spaces). It would he great if Xi supported this natively and I'd very much like to work on this, but I'm not quite sure how to implement this.

**Comment by cmyr** [comment]
This is a hard problem, and needs some thought, but yes it's a todo for sure. I thought there was an old issue open but I can't find it 😕

**Comment by Cogitri** [comment]
FWIW I implemented this now in gxi and I guess this is something that frontends should handle since it's very much dependent on them how they can draw this :)
