### ISSUE TITLE
[Question][xi-rope] find() - Avoid cloning regex 

### ISSUE THREAD

**Issue by ngortheone** [xi-editor/xi-editor#1146]
Hi, I am not a rust expert so I apologize for potentially stupid question.

I have a regex that is being heavily used. I follow recommendation from regex crate to
[avoid compiling in a loop](https://docs.rs/regex/1.1.2/regex/#example-avoid-compiling-the-same-regex-in-a-loop) :
```rust
lazy_static! {
    pub static ref REGEX_HEADLINE: Regex = Regex::new(r"\*+\s").unwrap();
}
```

I want to find a match in a rope
```rust
    fn next_headline() {
        let rope = Rope::from("Some text\n**** headline\n");
        let mut cur = Cursor::new(&rope, 0);
        let mut lines = rope.lines_raw(0..rope.len());
        find(
            &mut cur, &mut lines, CaseInsensitive,
            REGEX_HEADLINE.as_str(),
            &Some(REGEX_HEADLINE),
        );

```
but I get error 
```
error[E0308]: mismatched types
    |
144 |             &Some(REGEX_HEADLINE),
    |                   ^^^^^^^^^^^^^^ expected struct `regex::Regex`, found struct `data::REGEX_HEADLINE`
    |
    = note: expected type `regex::Regex`
               found type `data::REGEX_HEADLINE`
```
Ok, according to advice [here](https://github.com/rust-lang-nursery/lazy-static.rs/issues/119) I need to de-reference static ref, ok: `&Some(*REGEX_HEADLINE)`  but no luck again:
```
error[E0507]: cannot move out of borrowed content
    |
144 |             &Some(*REGEX_HEADLINE),
    |                   ^^^^^^^^^^^^^^^ cannot move out of borrowed content

```
I found the following way out: `&Some(REGEX_HEADLINE.clone())` and this time it works.

So I have the following questions:
1) Is there a better way to use lazy static with rope's find() function?

Also, the interface of `find` seems a bit unfriendly: 

2) Why do I need to provide string representation of regex `REGEX_HEADLINE.as_str()` when it is possible to hide it from the user?

3) Why does `find` want an owned regex instead of borrowed reference? I am not 100% sure, but isn't `clone()` copies the underlying data? If yes - that seems sub-optimal from performance viewpoint. 

4) Is it possible to change the signature of `find` to accept `regex: Option<&Regex>` instead of `regex: &Option<Regex>` - it seems like a bit more friendly way 

Thanks

**Comment by cmyr** [comment]
I agree, `Option<&Regex>` is the correct type signature. an `&Option<Regex>` can be converted to `Option<&Regex>` with `.as_ref()`.

**Comment by ngortheone** [comment]
@cmyr thanks for amazingly fast response!

**Comment by cmyr** [comment]
@ngortheone just good timing on your part, this is the day I'd set aside for xi stuff 😉
