### ISSUE TITLE
allow opening from command line as root

### ISSUE THREAD

**Issue by nhooyr** [xi-editor/xi-editor#1151]
Wanted to edit my `/etc/sudoers` file with `visudo`.

I use `xi` as my `$EDITOR` for everything.

Unfortunately, `sudo xi` doesn't open a file as root, it'd be nice if it just worked.

**Comment by yory8** [comment]
AFAIK the best practice is to use `sudoedit`, which runs the editor as current user, then replaces the file as super.

**Comment by nhooyr** [comment]
That makes perfect sense. Maybe `xi` should warn a user when ran as root? Though, if you use `sudo -s`, it should just work imo.

**Comment by mikaelmello** [comment]
> Maybe xi should warn a user when ran as root?

I agree with that. If that's the intended behavior from the mantainers I can do a PR in the following week

**Comment by Cogitri** [comment]
IMHO the entirety of Xi should _never_ be run as root. Maybe we could have some mechanism to do something similiar to `sudoedit` though (copying the root-writeable file to somewhere our user can write to (a temporary dir) and copying it back to the original location when the user has saved the file)?

FWIW I use the following script which does basically that to edit root-owned packages via gxi: https://gist.github.com/7ef511b8ca22d1c4abb6ed0dd392c624.

**Comment by Peltoche** [comment]
> IMHO the entirety of Xi should _never_ be run as root. Maybe we could have some mechanism to do something similiar to `sudoedit` though (copying the root-writeable file to somewhere our user can write to (a temporary dir) and copying it back to the original location when the user has saved the file)?

I like the idea. One of my question lately was: If I run a single server accessible for several users, how I handle the different user permissions? You proposition would be a possible solution: The server save the new file somewhere and the client (run by with the user permission) would move the new file to the place to the old one. The issue this solution don't fix is: If the server doesn't have the root permissions, how does it open the files with the read permissions available only for the root?

**Comment by Cogitri** [comment]
> The issue this solution don't fix is: If the server doesn't have the root permissions, how does it open the files with the read permissions available only for the root?

Although I don't really like this the only way to do this that comes to my mind is to ask frontend to copy the file somewhere. There are many different ways to open root owned files (e.g. on Linux there's polkit and that in itself has about a bazillion ways to be used, I looked into doing something like that in gxi, see https://github.com/Cogitri/gxi/issues/121) and about all of them are platform specific. Frontends could even implement just asking for the root password directly to copy it (although that'd suck)

**Comment by cmyr** [comment]
Just a thought, but maybe we could implement this in the CLI itself, with a like `--sudo` option, where the CLI handles the copy and prompts for the password?

**Comment by nhooyr** [comment]
How about if it’s ran as root, the binary calls itself with sudoedit?

**Comment by Cogitri** [comment]
> How about if it’s ran as root, the binary calls itself with sudoedit?

I don't quite calling sudoedit for this, when this is very dependant on the user having A) sudo installed and B) being in the sudoers file. I personally use doas instead of sudo. Also, on Linux using Polkit is way better integrated into desktops and is the generally accepted way to do stuff for elevating permissions.

**Comment by nhooyr** [comment]
Seems fine to me then to just do the right thing when ran as root instead of calling out to `sudoedit`. Create a temp file, then have the frontend edit that and then rename.

**Comment by cmyr** [comment]
and neither sudoedit nor doas are available on macos by default (afaik?), so I'm not sure what the best behaviour is there.

**Comment by nhooyr** [comment]
Thats fine. When running as root, xi can just create a temp file, make the frontend edit that, then rename that to the original file. This would work on every OS.

**Comment by Cogitri** [comment]
>  so I'm not sure what the best behaviour is there.

Well, as far as I can see there are two options:

* Use platform specific helper programs (polkit on Linux, UAC on Windows I guess, dunno what MacOS uses) and let the frontend copy the file somewhere. This way there's no way for permission escalations of Xi to occur and we're on the safe side - the frontend will need some safe way for the copying to be done though.

* What I'd personally prefer: Let Xi have a helper program (xi-su?), which the frontend runs as root (gaining the root permissions however it likes, e.g. via the previously mentioned methods), which does the file copying. I'd _very_,_very_ much like to not run the entirety of Xi as root, but only a small, separate helper program, as that leaves less attack surface. This opens the way for vulnerabilities in the helper program (but not Xi itself), but since we'd have on implementation across all frontends we should hopefully have enough people looking at this to make sure it's OK.

**Comment by yory8** [comment]
Aren't people who need to edit files as root mostly power user? In that case, maybe a simpler approach would be fine:  if I run xi as root, it exits with an error, with info about why it's an hazard to run complex non-core programs as root, and redirecting to a simple helper script that does what sudoedit does (which really can be implemented in just a few lines of shell or python or whatever; even if sudoedit is not installed, one can just do it by himself).

**Comment by Cogitri** [comment]
> Aren't people who need to edit files as root mostly power user? 

No, at least on Linux it's entirely plausible that non "power users" have to edit a config file or two sometimes :/

**Comment by cmyr** [comment]
The more I think about this the more complex it's starting to feel, and the more it would require a careful platform-specific implementation.

**Comment by Cogitri** [comment]
> The more I think about this the more complex it's starting to feel

Hm, root access isn't easy, so we should really keep this as simple as possible. I'd prefer if the frontend would just call some helper binary Xi provides as root which does the copying and nothing else.

> and the more it would require a careful platform-specific implementation.

Yes, but that (the permission elevation of the helper binary) will have to be handled by frontends.

**Comment by nhooyr** [comment]
Going to close as it has been a while and I'm not sure if this is relevant anymore.
