### ISSUE TITLE
xi-trace + xi-trace dump: intent to publish. 

### ISSUE THREAD

**Issue by bzm3r** [xi-editor/xi-editor#1153]
In order for xi-trace and xi-trace-dump to be used by other projects (e.g. druid-shell) which intend to publish on crates.io, it is necessary that xi-trace and xi-trace-dump also be on crates.io. I intend to push this forwards, and will make @raphlinus and @cmyr owners as soon as the crates are published. 

There is a [GSoC project](https://xi-editor.io/gsoc.html#xi-trace-cleanup) idea to perform cleanups and updates to xi-trace/xi-trace-dump mentored by @cmyr, but publishing version 0.1 of xi-trace/xi-trace-dump should not hinder this process.

Before publishing, we could also consider putting together xi-trace and xi-trace-dump as modules within a single crate. Are there any thoughts on this?

Other comments and concerns are most welcome.

**Comment by cmyr** [comment]
Realistically I do think that xi-trace-dump belongs in xi-trace; I think it's pretty meaningless on its own, and can go behind a feature flag if necessary.

If that isn't too much work, I'd go ahead and make that change first? But I'm not sure it's trivial.

**Comment by bzm3r** [comment]
please note: https://crates.io/crates/xi-trace

**Comment by cmyr** [comment]
cool, feel free to close this whenever.
