### ISSUE TITLE
error decoding file: XXXX

### ISSUE THREAD

**Issue by ab2h** [xi-editor/xi-editor#1172]
macOS Mojave 10.14.3
xi-mac
xi  XXXX.csv (GB18030)   
    error decoding file: XXXX

**Comment by jansol** [comment]
xi-editor won't open files that aren't valid UTF-8

**Comment by jansol** [comment]
This is by design and won't change unless someone adds automatic character set detection and transcoding to UTF-8. (Because we use Rust's String type internally and that is guaranteed and required to always be UTF-8)

**Comment by cmyr** [comment]
Agree this is not a bug, support is currently limited to valid utf-8. The tracking issue for encoding support is #794.
