### ISSUE TITLE
Have a better process to update deps

### ISSUE THREAD

**Issue by Cogitri** [xi-editor/xi-editor#1191]
Right now we just do massive 'update deps' commits from time to time. I'd personally suggest using [dependabot](https://dependabot.com/) for automatic version bumping, one at a time. I use it e.g. for gxi and it's super helpful for ensuring my deps stay up-to-date and also makes `git blame` a whole lot more useful if a dep breaks.

**Comment by cmyr** [comment]
Interesting, that does look like it could be useful. Are you interested in trying to set it up? What would you need, in terms of permissions?

**Comment by Cogitri** [comment]
Ah, I think you can set that up yourself, it's pretty simple and I'd need access to the org to set it up otherwise :)

**Comment by Cogitri** [comment]
I guess updating before releases is fine for now if we do more frequent releases :)
