### ISSUE TITLE
language_changed can send `""` as  new language

### ISSUE THREAD

**Issue by Cogitri** [xi-editor/xi-editor#1194]
I'm honestly not sure if this is expected behavior, but shouldn't it send 'Plain Text' instead? At least in gxi I just redirect `""` to `Plain Text`.

**Comment by cmyr** [comment]
I agree that a real default makes sense.

**Comment by Cogitri** [comment]
Should the default be `None` or `Plain Text`?

**Comment by cmyr** [comment]
I think `Plain Text` is good? I think we even include the `Plain Text` syntax definition by default, would have to check that though.

**Comment by Cogitri** [comment]
> I think we even include the Plain Text syntax definition by default

`Plain Text` has a syntax? I thought that'd just be the "no syntax selected" setting basically.

**Comment by cmyr** [comment]
Yea, "Plain Text" is a syntax; it doesn't do much, but it can be used to indicate that a file isn't code, and so maybe should have spell-check enabled, for instance.

**Comment by Cogitri** [comment]
Alright, I guess the default should be `None` then. About spellchecking: that isn't functional yet, right? I guess I might make a plugin for that.

**Comment by cmyr** [comment]
yea, this is more about the 'base scope' that a syntax provides. the scope for plaintext is `text.plaintext`, (markdown is `text.html.markdown`, rust is `source.rust`) and this lets plugins check if a particular document region is text vs source code.

**Comment by Cogitri** [comment]
Hm, should we rework `LanguageId` to be `Option<LanguageId>` everywhere (the proper, but more annoying way, I guess, especially since I'm not sure if this means something bad for plugins?), or should we just do `let lang = if self.language == "" { None } else { Some(self.language.as_ref()) }` when sending the RPC to the frontend?

**Comment by cmyr** [comment]
I'm not sure i understand; we shouldn't be sending an `Option` to the frontend I don't think. I would prefer to just send `"text"` as a default; if the syntax isn't recognized nothing bad will happen. Alternatively we could maybe just not send `language_changed`, I'm not sure if it's expected or not?

**Comment by Cogitri** [comment]
> we shouldn't be sending an Option to the frontend I don't think

Oh, alright, but that seems the clearest and easiest to me, I think. `Text` for no syntax highlighting seems odd to me, a `None` would clearly indicate that no lang has been chosen.

> I would prefer to just send "text" as a default; if the syntax isn't recognized nothing bad will happen.

That'd be rather confusing though, it's not exactly straightforward what's the difference between Plain Text and Text (if you don't know that the former is supplied by syntect whereas the latter isn't).

> Alternatively we could maybe just not send language_changed

Hm, at least Tau expects to receive `language_changed` on startup to set the intial lang, but it'd be easy enough to send `set_language` on startup for the same behaviour (and that'd also hand the default lang selection over to the frontend, which might be a good idea?). I think that that'd be a rather hidden change though which might break frontends in subtle ways (maybe we should just start doing a CHANGELOG-FOR-FRONTENDS.md ?)

**Comment by cmyr** [comment]
Yea, replace "Plaintext" for "text" as needed in my post above. My main thinking is just: having an unsupported syntax does not hurt anything, and it's conceptually clearer if we just say "every buffer has a syntax".

**Comment by Cogitri** [comment]
Yup, I'd be in favour of just setting "Plain Text" as default.
