### ISSUE TITLE
Move editing functions out of editor.rs

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#1199]
Similar to #1198, we would like to be able to use editing functions independently of an `Editor` or a runloop.

For more detail, see #1187. For an illustration of how this could be done, see the [`edit_ops` mod in the `xi-modal` branch](https://github.com/cmyr/xi-editor/blob/xi-modal/rust/core-lib/src/editor.rs#L955). (Note that having this be in a submodule of editor.rs isn't desirable long term).

A goal of this work should be to make it much easier to write simple tests of various edit operations.

**Comment by KeeganMyers** [comment]
I am a relative beginner to rust and completely new to the code base. Would this be a decent 1st PR opportunity or should I look into another issue? If so I can probably start looking at this over the weekend.

**Comment by cmyr** [comment]
This is definitely a little bit of a project, but it isn't crazy, and the linked resources will be useful. It would certainly be a good way to become more familiar with the codebase.

**Comment by Iamshankhadeep** [comment]
I am new to this community and rust, Can I work on this issue?

**Comment by nangtrongvuon** [comment]
@Iamshankhadeep Sure, feel free to dive into this and ask around on the xi zulipchat if you need help!

**Comment by Iamshankhadeep** [comment]
@nangtrongvuon sorry I am a little bit busy with something so I will start working on it this Sunday . Is it okay?

**Comment by TDecki** [comment]
I think this issue can be closed now.

**Comment by LiHRaM** [comment]
Yep!
