### ISSUE TITLE
scroll_to with multiple cursors

### ISSUE THREAD

**Issue by msirringhaus** [xi-editor/xi-editor#1206]
When working with multiple cursors, the protocol seems a bit confusing regarding cursor-positions. 

When having multiple cursors and issuing a `move` command, I get an `update` and a `scroll_to` response. 
`update` provides the position for all cursors, `scroll_to` only for one.

Shouldn't `scroll_to` also contain all cursors, to indicate to the frontend where it should scroll all cursors to? 

Or is the frontend supposed to parse `update` to update all cursor-positions and use `scroll_to` only to keep track of which is the "main cursor" ?

Edit: Probably related to #1139

**Comment by cmyr** [comment]
`scroll_to` describes a position in the buffer that should be made visible in the view; it does not indicate cursor movement.

`update` describes a set of changes to the line cache, which includes cursor positions.

When the frontend sends a movement command, it applies to all cursors.

`scroll_to` is a bit coarse. I believe at the moment it prioritizes the last cursor (the last cursor is always visible after a movement, but the first cursor may not be) but this is arbitrary.

Let me know if this isn't clear!

**Comment by msirringhaus** [comment]
Yes, thank you very much! This can be closed from my side.

**Comment by Cogitri** [comment]
Alright 👍
