### ISSUE TITLE
Scroll text not smooth when using mouse wheel

### ISSUE THREAD

**Issue by dimitre** [xi-editor/xi-editor#1211]
I'm using a microsoft optical mouse with wheel, and scrolling is truncated when using the wheel to scroll the text.
when using scrollbar it is smooth.
Thank you!

## Details

_If your issue is a build or runtime error, please include the following:_
- OS / platform (e.g. macOS 10.13.2)
macOS 10.14.5
- rust compiler version (`rustc --version`) (we test against the latest
  stable release)
rustc 1.36.0 (a53f9df32 2019-07-03)
- rust compiler installation method (e.g. rustup, homebrew, source)
rustup

**Comment by Cogitri** [comment]
I think this is more an issue in xi-mac than xi-editor?

**Comment by dimitre** [comment]
Indeed @Cogitri , should I close here and open there?

**Comment by Cogitri** [comment]
Yes please :)
