### ISSUE TITLE
package ID specification `xi-syntect-plugin` matched no packages

### ISSUE THREAD

**Issue by tuananh** [xi-editor/xi-editor#1214]
# Xi-Editor Issue Template
- [x] I have searched existing issues and could not find my issue.
- [ ] I have studied the documentation.

## Details

macOS 10.14.5
rustc 1.36.0 (a53f9df32 2019-07-03)
rustup
source commit id fb9f67e8061490027671793d1fa8287b49f5c4c9

build error

```
Compiling xi-core v0.2.0 (/Users/anh/code/xi-mac/xi-editor/rust)
    Finished release [optimized] target(s) in 2m 12s
error: package ID specification `xi-syntect-plugin` matched no packages
```

## Expected vs Actual
When describing an issue, it is very helpful to first describe expected behavior, followed by the actual functionality. See the following example:

_Note that backticks can be used to escape code both inline and in blocks._

    Expected `xi-core -v` to provide version.
    ```
    $ xi-core -v
    xi-core 0.2.0
    ```

    Actual: xi-core skips printing out the version and starts taking input
    ```
    $ xi-core -v
      <-------- xi-core waits on input there
    ```

**Comment by Cogitri** [comment]
Does jt work now?

**Comment by tuananh** [comment]
yes. sorry. false alarm

**Comment by Cogitri** [comment]
Alrighty 👍
