### ISSUE TITLE
Tell the frontend what lineending is used

### ISSUE THREAD

**Issue by Cogitri** [xi-editor/xi-editor#1215]
It'd be nice if xi told the frontend what linending is used for a document (and give it a possibility to set this) so that frontends can:

A) Display this to the user
B) Allow him to set different lineendings
C) To allow the frontend easier string manipulation (e.g. Tau needs to know the lineneding to check for trailing spaces/tabs)

**Comment by Cogitri** [comment]
I guess this falls under #1187 too

**Comment by cmyr** [comment]
Isn't this reported in the `config_changed` RPC?

**Comment by cmyr** [comment]
Basically the frontend should receive a notification for the config settings of each view, and this should be updated when those settings change; if that isn't happening it's a bug.

**Comment by Cogitri** [comment]
Derp, my bad, somehow I didn't see that. Thanks for the pointer :)
