### ISSUE TITLE
Supporting saving after X seconds of inactivity

### ISSUE THREAD

**Issue by Cogitri** [xi-editor/xi-editor#1216]
I really like this feature of IntelliJ IDEs and feel like it'd be nice of have in Xi too. I guess this should be done via a config option?

**Comment by Cogitri** [comment]
Hm, to be honest I'm a bit lost how to implement this in Xi, do you happen to have an idea, @cmyr ? I guess we'd need to spawn a timer for X seconds when one of the insert* functions is called, or is there something else that's always called when modification are done?

**Comment by cmyr** [comment]
This is a good question. I personally think having the editor overwrite user data without being asked is bad UX; to me the real solution is to privately stash unsaved changes, which can then be reloaded. This was worked on briefly (#939, #1014) but has been abandoned. It's definitely something I'd like to have, though.

**Comment by Cogitri** [comment]
Hm, I guess I might just call save manually then if Tau goes out of focus for a few secs, I'll work on making save a request then :)
