### ISSUE TITLE
Sometimes (at start?) plugin_started isn't sent

### ISSUE THREAD

**Issue by Cogitri** [xi-editor/xi-editor#1217]
So, after some digging I found out that `plugin_started` is usually called in `connect_plugin`. The problem is in line 908 in core_lib/src/tab.rs:

```
self.iter_groups().for_each(|mut cx| cx.plugin_started(&plugin);
```

At startup we don't have any views yet, so this isn't executed. Should we wait for views here, or maybe we should send plugin_started for a new view when it's created anyway? I only tested this with the syntect plugin.

CC @cmyr

**Comment by cmyr** [comment]
good point. Yes, I think that anytime a plugin attaches to a view it should notify the view; so maybe the correct place to put this isn't in `plugin_started`, but in wherever we tell the plugin about views? this should make it pretty easy to guarantee that if a plugin knows about a view, the view knows about the plugin.

**Comment by Cogitri** [comment]
> maybe the correct place to put this isn't in plugin_started

I think you kean connect_plugin?

Sounds good to do it when the plugin is told about the views.

**Comment by Cogitri** [comment]
Found the thing, will make a PR once I have internet on my laptop
