### ISSUE TITLE
Word wrap is broken

### ISSUE THREAD

**Issue by sjoshid** [xi-editor/xi-editor#1219]
- [x] I have searched existing issues and could not find my issue.
- [x] I have studied the documentation.
- [x] I get this issue on multiple frontends including Xi mac.

Open prefs and make sure `word_wrap` is true. 
Open Xi and start typing till you reach end of line. 

Expectation: When you reach end of line a soft break will take you to "next" line. 
Actual: Xi allows you keep typing past the window width ignoring `word_wrap`. 

FYI lines are correctly wrapped/unwrapped when the `word_wrap` is set to true/false.

**Comment by Cogitri** [comment]
What frontend are you using?

**Comment by sjoshid** [comment]
Tried two. Xi Mac and Tau. I’ll update the description when I get to my
computer.

**Comment by Cogitri** [comment]
![Screenshot from 2019-08-05 22-10-03](https://user-images.githubusercontent.com/8766773/62492042-cbfc5080-b7cd-11e9-8bda-c4f5edba3b5e.png)

Seems to work for me at least. Keep in mind it only wraps at words (so after a space).

**Comment by sjoshid** [comment]
![XiWrapping](https://user-images.githubusercontent.com/6751090/62501818-766a7880-b7ba-11e9-8ae4-480ba8a1c53b.gif)

**Comment by Cogitri** [comment]
You don't have a space in there, so it's not a word :)

It's word wrap, not text wrap.

**Comment by cmyr** [comment]
@Cogitri's explanation is correct: for linebreaking to occur, there needs to be a valid break position. If you type a contiguous string, there is no valid break position so we will not break.

To go deep on line breaking, check out [UAX #14](http://www.unicode.org/reports/tr14/tr14-43.html).

**Comment by sjoshid** [comment]
Im using Xi a lot more than I used to...that's when I ran into this issue. But I compared this feature with other major editors like vs code and sublime and both show correct behavior. And in both the pref is called "Word wrap"...not text wrap..not line wrap. 
So instead of saying "Word wrap is broken" should I say "Implement word wrap"? Or this is not an issue at all? There is something definitely fishy here.

**Comment by Cogitri** [comment]
Yes, it's word wrap, so it wraps words, not a line and words are usually divided by a space, so we only wrap if there's a space in between. I guess you're searching for syllables breaking?

**Comment by cmyr** [comment]
There is the concept of "emergency breaking", where even if there's no valid line break you just pick somewhere in the line and break anyway, but this is another chunk of work and it doesn't seem that important to me.

Is there a real-world situation where this is a problem for you? To me it feels like at worst an aesthetic issue.

**Comment by sjoshid** [comment]
Although not a real-world scenario...I thought maybe we can be in sync with other latest, widely used editors. But I agree with you both and can close this. Got to know `word-wrap` a bit more. Thank you.

**Comment by cmyr** [comment]
Yea, I think that we would like to eventually implement "emergency breaks", but we can treat that as a separate feature. 😁
