### ISSUE TITLE
'new_view' + 'set_theme' cause an assertion failure in linewrap.rs 

### ISSUE THREAD

**Issue by c4eater** [xi-editor/xi-editor#1232]
Hi,

I have encountered a data race between finalize_new_views() and do_set_theme() in CoreState, which results in a debug assertion failure in linewrap.rs.

This data race is triggered by the following simple sequence of rpcs:

1. client_started
2. new_view with params: {"file_path":"/path/to/some/file"} (file should be nonempty)
3. set_theme

See test update in c4eater/xi-editor@7dd6b40d36cbcac3aba3e990931a87aa5ff7a644 that demonstrates the issue. An attempt to run the updated test "test_state" in core_lib (in a **debug** build) will result in the following output:

```
thread 'test_state' panicked at 'assertion failed: `(left == right)`
  left: `935`,
 right: `0`', core-lib/src/linewrap.rs:685:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: std::panicking::begin_panic_fmt
   7: xi_core_lib::linewrap::MergedBreaks::new
             at core-lib/src/linewrap.rs:685
   8: xi_core_lib::linewrap::Lines::iter_lines
             at core-lib/src/linewrap.rs:192
   9: xi_core_lib::view::View::send_update_for_plan
             at core-lib/src/view.rs:796
  10: xi_core_lib::view::View::render_if_dirty
             at core-lib/src/view.rs:866
  11: xi_core_lib::event_context::EventContext::render
             at core-lib/src/event_context.rs:371
  12: xi_core_lib::event_context::EventContext::render_if_needed
             at core-lib/src/event_context.rs:357
  13: xi_core_lib::tabs::CoreState::notify_client_and_update_views::{{closure}}
             at core-lib/src/tabs.rs:463
  14: core::iter::traits::iterator::Iterator::for_each::{{closure}}
             at /usr/src/rustc-1.34.2/src/libcore/iter/traits/iterator.rs:604
  15: core::iter::traits::iterator::Iterator::fold::{{closure}}
             at /usr/src/rustc-1.34.2/src/libcore/iter/traits/iterator.rs:1684
  16: core::iter::traits::iterator::Iterator::try_fold
             at /usr/src/rustc-1.34.2/src/libcore/iter/traits/iterator.rs:1572
  17: core::iter::traits::iterator::Iterator::fold
             at /usr/src/rustc-1.34.2/src/libcore/iter/traits/iterator.rs:1684
  18: core::iter::traits::iterator::Iterator::for_each
             at /usr/src/rustc-1.34.2/src/libcore/iter/traits/iterator.rs:604
  19: xi_core_lib::tabs::CoreState::notify_client_and_update_views
             at core-lib/src/tabs.rs:458
  20: xi_core_lib::tabs::CoreState::do_set_theme
             at core-lib/src/tabs.rs:449
  21: xi_core_lib::tabs::CoreState::client_notification
             at core-lib/src/tabs.rs:319
  22: <xi_core_lib::core::XiCore as xi_rpc::Handler>::handle_notification
             at core-lib/src/core.rs:115
  23: <xi_rpc::RpcLoop<W>>::mainloop::{{closure}}


<...etc>
```

Debugging shows the following:

RPC "new_view" launches do_new_view(). In the end, this function initiates an asynchronous idle call to finalize_new_views() and returns.
Then do_set_theme kicks in, and the execution flow ends up in  inewrap::MergedBreaks::new().
An assert in this new() method expects the line breaks to be initialized, which is not true in this particular case: they are initialized in finalize_new_views() which has not been called yet.

I don't have a strong opinion on how to fix this in the right way, but a straightforward immediate call to finalize_new_views() in the end of do_new_view() seems to do the job (see c4eater/xi-editor@1e60c5ae18748cd972a3cd5f9970395386167c12).

**Comment by c4eater** [comment]
Apologies, I take back the proposal to make an immediate call to finalize_new_views. I overlooked some test failures caused by this change. This approach is wrong because finalize_new_views emits some **notifications** (eg available_themes) before the **response** for new_view, which violates the standard.

I'll update my PR shortly. Will make an attempt to split finalize_new_views into an "immediate" part (actual initialization of views) and an "idle" part (send notifications).

**Comment by Cogitri** [comment]
No worries, thanks for working on this.

**Comment by cmyr** [comment]
Yea, this is annoying. line breaks are in a pretty shoddy state.

You're correct about the rationale for `finalize_new_views` being called in idle; we need to return from `new_views` and respond with the view identifier before we can start sending notifications.
