### ISSUE TITLE
Cargo install fails because of inconsistent crossbeam versions

### ISSUE THREAD

**Issue by mcobzarenco** [xi-editor/xi-editor#1240]
# Details
Running `cargo run install -f .` on master fails with the message below (I think this was caused by upgrading notify in this [commit](https://github.com/xi-editor/xi-editor/commit/0b15cfe11c24d0b5f6f4fe74956f7e7308a28fdd), I can build it successfully 1 commit before).

```
error[E0308]: mismatched types
   --> core-lib/src/watcher.rs:101:29
    |
101 |         let inner = watcher(tx_event, Duration::from_millis(100)).expect("watcher should spawn");
    |                             ^^^^^^^^ expected struct `crossbeam_channel::channel::Sender`, found a different struct `crossbeam_channel::channel::Sender`
    |
    = note: expected type `crossbeam_channel::channel::Sender<std::result::Result<notify::Event, notify::Error>>`
               found type `crossbeam_channel::channel::Sender<_>`
```
Environment
```
Ubuntu 18.04
rustc 1.38.0 (625451e37 2019-09-23)
```

**Comment by Cogitri** [comment]
Can you run cargo update and try again?

**Comment by mcobzarenco** [comment]
I have tried `cargo update` to no avail; it updates these `crossbeam` dependencies:
```
...
    Updating crossbeam v0.7.2 -> v0.7.3
      Adding crossbeam-channel v0.4.0
    Updating crossbeam-deque v0.7.1 -> v0.7.2
    Updating crossbeam-epoch v0.7.2 -> v0.8.0
    Updating crossbeam-queue v0.1.2 -> v0.2.0
      Adding crossbeam-utils v0.7.0
...
```
I'm happy to try to submit a PR to fix it if you could point me in the right direction, but it's not clear to me which 2 crates have conflicting crossbeam dependencies.

**Comment by Cogitri** [comment]
rpc expects a different version than core-lib apparently. Dunno why that happens though since both should use the same cargo.lock :thinking: 

A PR would be nice.
