### ISSUE TITLE
xi-unicode no_std support

### ISSUE THREAD

**Issue by mooman219** [xi-editor/xi-editor#1250]
`xi-unicode` source wise isn't using any `std` API that isn't also in `core`, and can otherwise be trivially given the `#![no_std]` annotation in its `lib.rs`. 

Is there any non-obvious reason why it isn't already marked as `#![no_std]`, or would it be alright to PR a patch to make it so?

**Comment by raphlinus** [comment]
If it works, I'd be happy for such a patch.
