### ISSUE TITLE
xi-editor build falling on linux

### ISSUE THREAD

**Issue by Lord-Remington-the-3rd** [xi-editor/xi-editor#1252]
cargo and rustc version 1.41.0
build args: cargo build --all --release
linux: 5.4.18-1-MANJARO

### **BUILD ERROR:** 
> error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
>   --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:38:1
>    |
> 38 | extern crate alloc;
>    | ^^^^^^^^^^^^^^^^^^^
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>   --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:51:5
>    |
> 51 | use core::mem::MaybeUninit;
>    |     ^^^^^^^^^^^^^^^^^^^^^^
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:298:12
>     |
> 298 |     Inline(MaybeUninit<A>),
>     |            ^^^^^^^^^^^^^^
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:319:28
>     |
> 319 |     fn from_inline(inline: MaybeUninit<A>) -> SmallVecData<A> {
>     |                            ^^^^^^^^^^^^^^
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:323:36
>     |
> 323 |     unsafe fn into_inline(self) -> MaybeUninit<A> {
>     |                                    ^^^^^^^^^^^^^^
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:398:45
>     |
> 398 |             data: SmallVecData::from_inline(MaybeUninit::uninit()),
>     |                                             ^^^^^^^^^^^^^^^^^^^
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:438:63
>     |
> 438 |                 let mut data = SmallVecData::<A>::from_inline(MaybeUninit::uninit());
>     |                                                               ^^^^^^^^^^^^^^^^^^^
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:474:45
>     |
> 474 |             data: SmallVecData::from_inline(MaybeUninit::new(buf)),
>     |                                             ^^^^^^^^^^^^^^^^
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:493:55
>     |
> 493 |         unsafe { SmallVec::from_buf_and_len_unchecked(MaybeUninit::new(buf), len) }
>     |                                                       ^^^^^^^^^^^^^^^^
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:512:51
>     |
> 512 |     pub unsafe fn from_buf_and_len_unchecked(buf: MaybeUninit<A>, len: usize) -> SmallVec<A> {
>     |                                                   ^^^^^^^^^^^^^^
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:674:55
>     |
> 674 |                 self.data = SmallVecData::from_inline(MaybeUninit::uninit());
>     |                                                       ^^^^^^^^^^^^^^^^^^^
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:741:55
>     |
> 741 |                 self.data = SmallVecData::from_inline(MaybeUninit::uninit());
>     |                                                       ^^^^^^^^^^^^^^^^^^^
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>     --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:1074:52
>      |
> 1074 |                     let mut data: MaybeUninit<A> = MaybeUninit::uninit();
>      |                                                    ^^^^^^^^^^^^^^^^^^^
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>     --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:1074:35
>      |
> 1074 |                     let mut data: MaybeUninit<A> = MaybeUninit::uninit();
>      |                                   ^^^^^^^^^^^^^^
> 
>    Compiling unicode-xid v0.1.0
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:307:42
>     |
> 307 |             SmallVecData::Inline(a) => a.as_ptr() as *const A::Item,
>     |                                          ^^^^^^
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:314:42
>     |
> 314 |             SmallVecData::Inline(a) => a.as_mut_ptr() as *mut A::Item,
>     |                                          ^^^^^^^^^^
> 
> error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:398:58
>     |
> 398 |             data: SmallVecData::from_inline(MaybeUninit::uninit()),
>     |                                             -------------^^^^^^
>     |                                             |
>     |                                             function or associated item not found in `core::mem::MaybeUninit<_>`
> 
> error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:438:76
>     |
> 438 |                 let mut data = SmallVecData::<A>::from_inline(MaybeUninit::uninit());
>     |                                                               -------------^^^^^^
>     |                                                               |
>     |                                                               function or associated item not found in `core::mem::MaybeUninit<_>`
> 
> error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:674:68
>     |
> 674 |                 self.data = SmallVecData::from_inline(MaybeUninit::uninit());
>     |                                                       -------------^^^^^^
>     |                                                       |
>     |                                                       function or associated item not found in `core::mem::MaybeUninit<_>`
> 
> error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:741:68
>     |
> 741 |                 self.data = SmallVecData::from_inline(MaybeUninit::uninit());
>     |                                                       -------------^^^^^^
>     |                                                       |
>     |                                                       function or associated item not found in `core::mem::MaybeUninit<_>`
> 
> error[E0599]: no method named `assume_init` found for type `core::mem::MaybeUninit<A>` in the current scope
>    --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:912:39
>     |
> 912 |                 Ok(data.into_inline().assume_init())
>     |                                       ^^^^^^^^^^^
> 
> error[E0599]: no function or associated item named `uninit` found for type `core::mem::MaybeUninit<_>` in the current scope
>     --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:1074:65
>      |
> 1074 |                     let mut data: MaybeUninit<A> = MaybeUninit::uninit();
>      |                                                    -------------^^^^^^
>      |                                                    |
>      |                                                    function or associated item not found in `core::mem::MaybeUninit<_>`
> 
> error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
>     --> /home/tinyman/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.0.0/lib.rs:1077:30
>      |
> 1077 |                         data.as_mut_ptr() as *mut A::Item,
>      |                              ^^^^^^^^^^
> 
> error: aborting due to 23 previous errors
> 
> Some errors occurred: E0599, E0658.
> For more information about an error, try `rustc --explain E0599`.
> error: Could not compile `smallvec`.
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> Error: module xi-core: Child process exited with code 101
>

**Comment by Cogitri** [comment]
Are you really sure you're using Rust 1.41? Those features should be stabilized since Rust 1.39. Whar does `rustc --version` return?

**Comment by Lord-Remington-the-3rd** [comment]
It returns 1.41. So I was confused as well

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Lord-Remington-the-3rd** [comment]
i am not confident on this but i think its because someone wrote MaybeUninit::uninit() instead of MaybeUninit::uninit<_>()

**Comment by Cogitri** [comment]
Works just fine for me.

```
rustc --version
rustc 1.41.0
```

**Comment by Lord-Remington-the-3rd** [comment]
Is my cargo defaulting to an earlier version of rust? Is there a way I can change that?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cogitri** [comment]
You can modify what version cargo uses with `cargo +nightly` or similar.
