### ISSUE TITLE
Problem with `Spans` modification.

### ISSUE THREAD

**Issue by wdanilo** [xi-editor/xi-editor#1276]
# Xi-Editor Issue Template
- [x] I have searched existing issues and could not find my issue.
- [x] I have studied the documentation.

## Details
Hi! I'm trying to use the `xi-rope` 0.3 crate based on its docs and the usages in `xi-editor`. As far as I understand, we can use `Spans` to mark some parts of the text with meta-information. So let's assume I want to mark the text with information whether it is bold or nor. Based on how `Annotations` and their tests are [defined in xi-editor](https://github.com/xi-editor/xi-editor/issues/1276#issue-640116440) I have created a very small example code:

```rust
    let mut spans : text::rope::Spans<bool> = default();

    let interval : text::rope::Interval = (0..3).into();
    let mut builder = text::rope::SpansBuilder::new(20);
    builder.add_span(interval,true);
    spans.edit(interval,builder.build());

    let interval : text::rope::Interval = (10..15).into();
    let mut builder = text::rope::SpansBuilder::new(20);
    builder.add_span(interval,true);
    spans.edit(interval,builder.build());

    println!("{:?}",spans.subseq(0..100).iter().collect_vec());
```

This simulates (or was meant to simulate) 2 user edits - making chars 0-3 bold, and later, making chars 10-15 bold. Unfortunately, the output is completely different than I suspected:

```rust
[([0, 3), true), ([20, 25), true)]
``` 

I would be very thankful for any hint where am I making the error. Moreover, I've got one more question (probably connected to the answer). When I'm changing `Spans`, do I need to user `SpansBuilder` for every change (is this the best way to do)? If so, what is the purpose of the `max_len` number passed to `SpansBuilder::new(...)`? Can I always just set it to the max offset of the currently created span?

**Comment by raphlinus** [comment]
Ok, I see what's going on here. The `edit` method is not doing what you think it is at all; you're probably thinking of it like a set of spans, expecting it to add a span with the same offsets. It might help for me to explain the semantic model provided by the `edit` operation.

Ignoring UTF-8 for now, a string is a sequence of ASCII characters, or a mapping from index to character. An interval tree is best thought of as a mapping from index to *set* of spans, where a span is included in the set if the index is included in the (closed-open) interval. So the edit operation does a string-like edit.

In particular, your second spans object is a string-like entity of length 20, where 0..10 has no spans, 10..15 has a span of value `true`, and 15..20 is again empty. What your edit operation is requesting is to take the first spans object and replace 10..15 in that with the second. So 0..10 have the same values as the original, 10..30 are the replacement, and 30..35 are the same as 15..20 in the first. This is consistent with what you're reporting.

Hopefully this explains the `max_len` as well. It's not a capacity, but instead indicates the length of the "tail" of the spans structure; if it's increased, there's a longer region empty of spans.

We were hoping to develop rich text capabilities, and I think the xi-rope spans object is a good low-level data structure for that, but I suspect that you'll need to write your own code for editing operations that match your needs, though a bunch of stuff can be done with the code that's there now. We've had a bunch of discussions over the years, a lot of it informed by Android SpannableStringBuilder - that has a whole mechanism for adding metadata to spans to indicate what the behavior is when inserting at span boundaries (the inclusive/exclusive distinction), and originally our Interval type was designed to incorporate that, but we ended up removing the functionality as part of a simplification. I still think it's possible and interesting to build this type of capability, and would take PR's for the parts relevant to xi-rope, but sadly cannot promise it would be simple.

Hope this helps!

**Comment by wdanilo** [comment]
@raphlinus Thank you for the super-detailed explanation. 

I see now where my confusion came from. One of my basic assumptions was incorrect - I was sure that the `interval` argument passed to `spans.edit` describes **both** what part we want to replace (correct), as well as which part of the builder we want to use (incorrect). Somehow such a design was natural to me so I was not even considering these assumptions are incorrect, but of course, the current design makes much more sense. I need to contribute some docs to the `edit` function!

Thank you for the additional explanation about the span boundaries handling. Luckily we would not need anything more than is provided right now. We have a lot of meta-information connected to the source code we keep in the rope, but they are managed by our engine when editing the text. For example, the colors are used for syntax highlighting only, so whenever we edit the text, we will regenerate spans for the current line (or a subset of it). The same applies to widgets (sliders, color choosers, etc inside of text). However, in case it would appear we need it integrated with spans, I would be very happy to contribute to xi-rope. Thank you for making it ❤️
