### ISSUE TITLE
xi-unicode: detecting break at end of string

### ISSUE THREAD

**Issue by dhardy** [xi-editor/xi-editor#1289]
`xi_unicode::LineBreakIterator` always reports a hard-break at the end of its input. Fine, but I need to know (for `kas-text`; also affects @alexheretic's `glyph-brush-layout`) whether my document ends with an explicit line-break or not. Is there a clean way to do this?

The `linebreak_property` fn is exposed but with no documentation as to its return value (and it's not easy to tell from the code's state machine look-up).

(There is also the question of whether one can even tell by looking at only the last char — though `\r\n` is essentially equivalent to `\n`.)

Perhaps the easiest solution is to match the last char against any of the [BK, CR, LF or NL classes](https://www.unicode.org/reports/tr14/#Table1)?

**Comment by raphlinus** [comment]
I think you can tell by looking at the last character, yes. Generally I tried to follow the ICU API here - I haven't taken a look right now because I wanted to respond quickly, but do you know if it does something special?

There are other possibilities of course, such as not reporting the break unless it is explicit, so relying on the caller to handle end of string (as an option so it wouldn't break existing uses).

**Comment by dhardy** [comment]
[This is my code](https://github.com/kas-gui/kas-text/blob/11266f71ca8dee93857aa2c0690f7bfcc3558290/src/prepared/text_runs.rs#L134) which seems to work but hasn't been thoroughly tested.

>  not reporting the break unless it is explicit, so relying on the caller to handle end of string

I guess this would be preferable for me. As it is I don't end up checking the last item returned from the iterator anyway (since it's guaranteed to be at the end of the text).

Quick (off-topic) question: what is the planned scope of `xi-unicode`, given the rather generic name?

**Comment by raphlinus** [comment]
From a quick look at your code, I think it's fine.

Having had another look at [Annex 14](https://unicode.org/reports/tr14/), I'm not sure there's a strong reason to change the code. I think it's reasonable to define the code as implementing the Unicode line break algorithm, which it does, and that has the EOT test before all others. It's also the case that TR14 is not the whole story, there's a bunch of stuff that can and should be done on top of it, including soft hyphens. ([Android](https://android.googlesource.com/platform/frameworks/minikin/+/refs/heads/master/libs/minikin/WordBreaker.cpp) also has a parser for url and email address, then there's the whole question about what to do for Thai and other scripts/languages that rely on dictionaries to break). So my first inclination is to say that explicit line breaks at EOT are just another instance of that, especially as adding a config flag increases the API complexity.

The xi-unicode crate was started a *long* time ago before there were a lot of Unicode crates. It's unlikely it will grow more functionality, as today it would probably go in unic or similar.

**Comment by dhardy** [comment]
Yup, makes sense. Thanks for the opinion.

I guess this means `linebreak_property` should not be part of the public API (or at least `#[doc(hidden)]`? It's completely unusable without documentation.

**Comment by raphlinus** [comment]
I think the line break properties follow ICU, so it's not a normative standard but probably de-facto. The best solution might be to document them, possibly with a bunch of constants (if I were writing it today, I might use a repr[u8] enum or a newtype, but I'm not sure the API breakage would be worth it). If nothing else, that would make the tests more readable. Looking at the code, I think the reason it's public is primarily the tests, so `#[doc(hidden)]` would be a reasonable approach to that - I didn't find any evidence of the property being used directly.

**Comment by raphlinus** [comment]
Thinking about this some more, I'm pretty convinced, and will shortly upload a PR.

Regarding the numeric properties, I'm going to document their meaning (ICU is an authoritative source). If I were inclined, I think it would be better to make it an enum, but that's a bigger code change for unclear benefit.

Thanks for bringing this up!
