### ISSUE TITLE
no such module 'ArgumentParser'

### ISSUE THREAD

**Issue by windowshome** [xi-editor/xi-editor#1297]
/Users/xuwei/Desktop/xi-mac/Sources/XiCLICore/Xi.swift:15:8: error: no such module 'ArgumentParser'
import ArgumentParser
       ^

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by Cogitri** [comment]
This is a xi-mac and not a xi-editor issue, could you please report this at https://github.com/xi-editor/xi-mac/issues ?
