### ISSUE TITLE
error code -32600 unknown variant `set_language`

### ISSUE THREAD

**Issue by sucrecacao** [xi-editor/xi-editor#1304]
# Xi-Editor Issue Template
- [X ] I have searched existing issues and could not find my issue.
- [X ] I have studied the documentation.

Send the following `set_language` request to xi-core:
`{"id": 1, "method":"set_language", "params" : {"view-id":"view-id-1", "language_id":"Rust"} }`

I got the following error:
```
{"error":{"code":-32600,"data":"unknown variant `set_language`, expected one of `edit`, `new_view`, `get_config`, `debug_get_contents`","message":"Invalid request"},"id":1}
```

I also tried without the `id` argument:
```
{ "method":"set_language", "params" : {"view-id":"view-id-1", "language_id":"Rust"} }
```
But I don't get any reponse ( it doesn't crash neither) .

What am I doing wrong ?

**Comment by Cogitri** [comment]
Hm, that should work, in `Tau` I send the following command to change the language:

```
{"method":"set_language","params":{"language_id":"D","view_id":"view-id-2"}}
```

And get the following response:

```
{ method: "language_changed", params: Object({"language_id": String("D"), "view_id": String("view-id-2")}) }
```

Keep in mind that you need the syntect plugin for this to work.

**Comment by sucrecacao** [comment]
> Keep in mind that you need the syntect plugin for this to work.

Ah I didn't know, it is not specified in the doc ( https://xi-editor.io/docs/frontend-protocol.html#set_language )

**Comment by Cogitri** [comment]
Ah, I should've worded that differently: Without the syntect plugin, [available_languages](https://xi-editor.io/docs/frontend-protocol.html#available_languages) will probably be empty and you can only set languages that are specified by `available_languages`. Would be better to document that in the docs since plugins other than syntect could provide that functionality.

**Comment by sucrecacao** [comment]
Any doc on how to install a plugin ? I can't see any on xi website

**Comment by Cogitri** [comment]
Just doing `make install in the `syntect-plugin` folder should do the trick,
