### ISSUE TITLE
add `#![feature(stdsimd)]` to the crate attributes to enable

### ISSUE THREAD

**Issue by vedon** [xi-editor/xi-editor#1311]
Hi, I can't run the test in multiset.rs  on my m1 macbook pro.  rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)

![image](https://user-images.githubusercontent.com/1811570/113406408-058bc180-93de-11eb-82b1-21e67f63fe79.png)

The error show below:

error[E0658]: use of unstable library feature 'stdsimd'
   --> rope/src/compare.rs:485:12
    |
485 |         if is_x86_feature_detected!("sse4.2") {
    |            ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #27731 <https://github.com/rust-lang/rust/issues/27731> for more information
    = help: add `#![feature(stdsimd)]` to the crate attributes to enable

**Comment by vedon** [comment]
I have added `#![feature(stdsimd)] to the crate, but it still not working.

**Comment by devillove084** [comment]
+1
