### ISSUE TITLE
Please remove "Xi" from name or rename to something else, this imply president's name, otherwise you'll get banned

### ISSUE THREAD

**Issue by snowman** [xi-editor/xi-editor#1335]
# Xi-Editor Issue Template
- [X] I have searched existing issues and could not find my issue.
- [ ] I have studied the documentation.

## Expected vs Actual
don't use `xi` in name or rename it to `ix-editor` or something else

**Comment by fightingcat** [comment]
Then I vote for Pooh-Editor or Winnie's Editor.

**Comment by lixiang810** [comment]
I don't even know whether you're joking about him or not.

**Comment by WhiredPlanck** [comment]
亲爱的朋友，这实在有点离谱，我不知道你是在讽刺还是发自真心地提出这个 Issue。我相信你肯定看得懂中文 …… 从老实人的角度我想说：请不要将自己的眼光太狭隘，狭隘到只能看见拼音的世界；也不要往本不应该附加政治意义的地方去强行附加政治意义。 X 开头的单词在英语世界里本就很少见（可以打开你的《牛津高阶英汉双解词典》，看看 X 开头的有多少页？），所以我想这个项目用 Xi 也是想表达与众不同的含义，而且在本项目介绍的第二行，就写着它的发音叫 Zigh。开源本就坎坷，请保持它应有的纯洁，不要再平添现实世界的纷扰。
