### ISSUE TITLE
How do you pronounce Xi?

### ISSUE THREAD

**Issue by marxo** [xi-editor/xi-editor#206]
A great and serious matter at hand, since we all know a new editor war is now upon us. We have to ask "oh great maintainers, what is the correct pronunciation of Xi?"

There must be a way for us to figure this out before it is too late!

**Comment by rkusa** [comment]
Raph gives an answer to that at about 18. second https://www.youtube.com/watch?v=SKtQgFBRUvQ#t=18s

**Comment by dlee** [comment]
He pronounced it "Zigh", which rhymes with "sigh".

**Comment by disordinary** [comment]
or rhymes with `vi` 😄

**Comment by vimuel** [comment]
In Brazil "xi" is an exclamation similar to "oh my" and is pronounced "shee". 😄

**Comment by shaunlebron** [comment]
let's add it to the README here: https://github.com/google/xi-editor/pull/376

**Comment by jonwolski** [comment]
Is it too late to propose "ee LEH ven?" 😀

**Comment by cateyes99** [comment]
Pretty sure it is exactly the same as the surname of the current China's President Xi Jinping 😄 so should be pronounced as the same Xi. If you don't know how to do the Mandarin pinxin, then the close pronunciation is `hsi` wow 😮

**Comment by chriskrycho** [comment]
@cateyes99 see the README for the actual pronunciation. It's like the English word "sigh" but with a "Z". 😄

**Comment by JoshRagem** [comment]
sorry, but, as an english speaker, the readme pronunciation hint is totally vague.
does it rhyme with z-eye? zig? zi*gutteral noises*? zee?
this convo indicates "rhymes with 'sigh'" so that sholud be the hint in the readme

**Comment by cmyr** [comment]
this is now in the readme.
