### ISSUE TITLE
Add click_count to drag command

### ISSUE THREAD

**Issue by ghost** [xi-editor/xi-editor#222]
The params for `drag` are: `[line, column, flag]`. 
In almost every text editor, selection acts differently depending on how many clicks preceded the drag (1 click = normal selection, 2 clicks = word selection, 3 clicks = line selection).

Two ideas:

* Maybe we could add a `click_count` param to the `drag` command just like the current `click` command has? 
* Or, perhaps a better method would be for the `drag` command to get the `click_count` from the last `click` command?

The main motive behind this is so the front-end and the core don't have conflicting patterns for things like `word_selection`, etc.

**Comment by cmyr** [comment]
I'm not sure I'm totally understanding.

On macOS, I *don't believe* that dragging is influenced by click count. I *do* agree that double clicking a word should select a word, and triple clicking a line should select that line, but this behaviour is currently implemented. If you drag after a double click, it selects a word with the double click and then modifies that selection with the drag: this is the same behaviour as in other apps, I think? 

Please let me know if I'm missing something!

**Comment by callodacity** [comment]
Yes it does affect it - I made a quick `gif` here, [check it out](http://g.recordit.co/b9q3NgAFZN.gif). The first time is after one click.
The second time is after a double click, and the last after a triple click.

The `gif` quality isn't the best but as you can see after a double click-and-drag it starts selecting by words, and after a triple click-and-drag, by lines.

**Comment by callodacity** [comment]
Here's a better example:
![untitled](https://cloud.githubusercontent.com/assets/1011648/25369580/50233ce8-29c8-11e7-98ac-9832c7040cc1.gif)

**Comment by cmyr** [comment]
Okay cool, I wasn't familiar with this behaviour, thank you for pointing it out.

This is an interesting situation where the behaviour may be platform specific, and we have to decide how to handle that, but I agree this is how we would ideally want to behave on the mac. 

It wouldn't be trivial to implement, but it isn't too bad. My thinking is we should hold off until some current changes to selection handling land (#211 and friends) but otherwise anyone who wants this is welcome to it.

**Comment by callodacity** [comment]
I just checked, and the behaviour is exactly the same on Windows (not just in browsers, but also natively). 👍

**Comment by cmyr** [comment]
Okay, that's great news. I pinged @sp3d & @eyelash, if this is also default in gtk than that's one problem gone.

**Comment by eyelash** [comment]
This is also the default behaviour for GTK+ :+1:

**Comment by cmyr** [comment]
Okay, after some discussion last night a few things:

- this should wait until the multi-sel stuff lands;
- we may want to more thoroughly refactor mouse-gesture handling, moving to a single event and an internal enum. This will also make it easier for us to implement things like hover support for tooltips, etc.

If anyone is eager to get started at this they're more than welcome, happy to help how I can.

**Comment by cmyr** [comment]
This is fixed in #785
