### ISSUE TITLE
refactor tests in python plugin lib, and run with travis

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#249]
There are currently a number of tests in the python plugin lib that I was running manually with [py.test](https://docs.pytest.org/en/latest/) during development. These should be pulled out into their own file(s), and travis should be configured to run them automatically.

**Comment by little-dude** [comment]
I could help with. Where are the exisiting tests?
And do you have a kind of test plan in mind already?

**Comment by cmyr** [comment]
all tests are currently in cache.py. Not sure I know what you mean by test plan? For additional tests, going forward?

**Comment by little-dude** [comment]
> For additional tests, going forward?

Yes exactly

**Comment by cmyr** [comment]
yea we haven't gone into that in too much depth. We would definitely like to do more testing. @cbrewster was talking about this a bit a while ago, in #193. 

One thing that I would like is regression tests against the RPC protocol itself, and eventually for the plugin protocol. Then there's lots of room for testing movement and edits, but we'd need some sort of harness such as discussed above. There might be simpler approaches, but I haven't looked into it too closely.

**Comment by Melvie** [comment]
@cmyr  Does this still need to be worked on? I'd like to help out!

**Comment by cmyr** [comment]
@Melvie sure! The python plugin lib is going to be getting a bunch of attention in july, so setting up proper testing for it would be welcome.

**Comment by Melvie** [comment]
@cmyr  Awesome. I've never used travis before so I'll have some learning to do there. But you mentioned all the tests being in cache.py and braking them up into their own files. Any advice as to how you'd break them up at all?

**Comment by cmyr** [comment]
@Melvie iirc there is currently exactly _one_ test. I'm not sure what best practices are for pytest, to be honest? but I suspect there should be a top level 'tests' directory? And I'd probably just add a single new file called like `test_cache.py` or something. But I'd personally just do some googling. I'm also not super familiar with travis, but there's lots of info available. :)

**Comment by Melvie** [comment]
@cmyr So, I have the travis yml set up properly and the pytests will run locally. But when rust builds on travis and  locally I get the following error after it runs **cargo build || exit**:
```
error[E0599]: no function or associated item named `load_defaults` found for type `syntect::highlighting::ThemeSet` in the current scope
   --> core-lib/src/styles.rs:156:22
    |
156 |         let themes = ThemeSet::load_defaults();
    |                      ^^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error(s)
error: Could not compile `xi-core-lib`.
To learn more, run the command again with --verbose.
```

Is this something I am doing wrong, or something else?

**Comment by cmyr** [comment]
@Melvie This error message is just saying that compilation is failing. That particular method is behind a feature flag in syntect. Can you run `cargo check` in `rust/core-lib`? If it fails try `cargo clean` and try again? And make sure you're up to date on master?

**Comment by cmyr** [comment]
This should be considered 'on hold' for now, the python plugin lib is stale.

**Comment by cmyr** [comment]
🐍🔫
