### ISSUE TITLE
`add_selection_above` and `add_selection_below` polish

### ISSUE THREAD

**Issue by eyelash** [xi-editor/xi-editor#328]
- Running `add_selection_above` with a cursor somewhere on the first line should not add a cursor to the beginning of the document.
- Running `add_selection_below` with a cursor somewhere on the last line should not add a cursor to the very end of the document.
- When a selection spans multiple characters we should probably add a selection that spans the same range on the line above/below like Atom does (what I previously called Atom behaviour). Here we would need to discuss what to do if the line above/below is shorter than the current line. Atom skips the line if there would be no overlap but still adds a cursor if the selection is a caret.
- Atom skips empty lines if the selection is not a caret on the first column.

**Comment by eyelash** [comment]
A few examples of Atom's behaviour:
Consider the following document:
```
abcd

ef
ghi
jklmn
```
If you add a cursor before `a` and call `add_selection_below`, a cursor on the empty line 2 will be added.
If you add a cursor between `a` and `b` and call `add_selection_below`, a selection between `e` and `f` will be added.
If you select `cd` and call `add_selection_below`, `i` will also be selected. If you call `add_selection_below` again, another selection will be added for `lm`.

**Comment by ishanjain28** [comment]
HI, I would like to work on this issue, From your description of how this feature should work, It looks like you are talking about the multiple cursor support that is available in VSCode, Atom or vim.

The rpc calls `add_selection_below` and `add_selection_above` are already used in xi-editor code to select the text below and above the cursor when Shift+Down/Up keys are pressed. 

So, I'd suggest naming them `add_cursor_below` and `add_cursor_above`. 

cc @cmyr, I want to work on adding multiple cursor support. I checked the code in core-lib but I can use some help in implementing multiple cursors.

**Comment by cmyr** [comment]
@ishanjain28 multiple cursor support is already implemented; this issue is about polishing two commands related to multi-cursor.

On xi-mac, this is mapped to <kbd>control</kbd>+<kbd>shift</kbd>+<kbd>↑</kdb> (or ↓). This adds a new cursor at the position of the current cursor, on the previous (or next) line.

If you play around with this, you can see the problem originally reported. Would be very happy to have you explore this, it shouldn't be too much work.

**Comment by ishanjain28** [comment]
@cmyr I would love to work on this issue but I am on arch linux and I use `xi-gtk` as the frontend, And it doesn't has support for multiple cursors.

**Comment by eyelash** [comment]
@ishanjain28 if you hold <kbd>Control</kbd> while left clicking you should be able to create additional cursors. Also <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Up</kbd> and <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Down</kbd> should add cursors above and below the current cursors.

**Comment by ishanjain28** [comment]
Thanks for responding @eyelash. I think my i3 config is interfering with xi-gtk shortcuts. I'll fix my i3 config and then work on this issue.

**Comment by timpbrenner** [comment]
I would like to take a swing at this. I think I have a handle on the source enough to try to make my first contribution.

**Comment by timpbrenner** [comment]
I just created the PR: https://github.com/xi-editor/xi-editor/pull/906 I look forward to feedback.

**Comment by cmyr** [comment]
closed by #906
