### ISSUE TITLE
Autodetect tab and newline settings when opening a file

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#411]
We will shortly have the ability to set per-buffer overrides of these settings, and it would be a nice little win if we could (optionally) set them automatically when loading a new file.

As a bonus we could also check for mixed newlines, and throw a warning to the client. Extra bonus would be to be able to fix the problem. 😮

**Comment by cmyr** [comment]
@bemeurer Some additional notes:

The bulk of this work will be some function that takes a string (the contents of a file loaded from disk) and tries to guess the whitespace settings for this file.

Offhand, I could imagine the results of this function being 'unclear', 'spaces(n)', 'tabs', and 'mixed'? This latter may be outside the scope of this issue, but it's something we might want to show the user.

The funny bit:

we want a new setting, `autodetect_whitespace`. The value for this setting should determine whether we bother with running this function, or not.

We'll need to know the value for this setting (which might be influenced by what syntax we're in) in order to decide if we're using the detected values. So we'll either need to generate the config twice (once to figure out the value for `autodetect_whitespace`, and then once after we've overridden the whitespace settings for this document) or we'll need to add something to `ConfigManager` that finds the value without generating the whole config. (This will need to know the syntax and the view_id, probably).

If we're modifying the whitespace, the way we'll do that is by calling `ConfigManager::update_user_config` with the `SysOverride` domain, and the new values for `tab_size` and `translate_tabs_to_spaces`.

I imagine you will be working in the `new_view_with_file` fn in `core-lib/tabs.rs`
The config stuff is all pretty new, so this will be an opportunity to see how easy it is to work with. We may discover some things that need to be rethought.

Let me know if anything here isn't clear; I am happy to answer questions.

**Comment by LiHRaM** [comment]
I'd like to take this one. :)
