### ISSUE TITLE
Add 'dialog' RPC

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#438]
For presenting a dialog box to the user.

- Dialogs should be limited to two options
- This could possibly replace the current `alert` RPC?
- This would probably be a sync request, returning the index of the selected item?

Here's a sketch of how this might look in JSON; this isn't very fleshed out, just the basic idea.

```js
{  
   "method":"show_dialog",
   "params":{  
      "message":"File has changed on disk.",
      "info":"The file was changed by another process. Do you want to load the changed file?",
      "buttons":[  
         {  
            "title":"Reload",
            "type":"default"
         },
         {  
            "title":"Cancel",
            "type":"cancel"
         }
      ]
   }
}
```

Button types would be an enum, with "cancel", "default", and "option", and "destructive" members  (maybe others?), and would be a guide to clients; "cancel" might be associated with <kbd>esc</kbd>, "default" might be colored differently and associated with <kbd>return</kbd>, etcetera.

**Comment by daubaris** [comment]
Hi, is this issue still relevant?

**Comment by Cogitri** [comment]
Hm, this seems rather annoying to implement in frontends, I think I personally prefer `alert`, which sends an error message to be displayed (which can be ignored) and an error code (which is more useful, since the error msg might have to be localized), which also leaves the frontend more freedom to decide what to do with the error.

**Comment by cmyr** [comment]
yes I'm happy to close this, I remember having a concrete motivation when I opened it but I do _not_ remember what that was. :)
