### ISSUE TITLE
Lets attach Beginner/Intermediate/Advanced tags to Help Wanted tags

### ISSUE THREAD

**Issue by zachdaniel** [xi-editor/xi-editor#505]
Looking to dive in, and in libraries that provide those tags make it *very* easy to know where to look for something manageable. Just an idea! If there is a better place for discussion, feel free to delete this and point me there.

**Comment by cmyr** [comment]
Agreed there is room for improvement in how we tag issues. We do have an 'Easy' and a 'Help Wanted' tag, although we don't use them too too often. Realistically we have a lot of work to do to make the project easier to contribute to, but that should hopefully improve in the next month or so.

I'm less sure of the usefulness of 'intermediate' & 'advanced' tags; I suspect that once someone has been contributing a bit and hanging out on IRC they'll have a better sense of the scope of various problems. But maybe a 'ready' tag would be helpful? I'm really curious if there are any good resources/best practices out there around this (contribution management).

**Comment by zachdaniel** [comment]
Thats a good question about best practices/resources. I haven't personally read up on the subject so I don't know if anyone has really standardized it. For my specific suggestion, I've seen it succeed in other repos (like github.com/elixir-ecto/ecto), but perhaps the main win is the `Easy` tag. The big thing is finding a hands on entry point to a project when you want to start contributing to it. I usually just go to a project, scan issues until something sounds easy enough to start hacking.

With that said, if you're still hashing out the processes around contributions and stuff, comprehensive tagging of issues probably isn't top priority! :)

**Comment by cmyr** [comment]
going to close this, we can revisit in the future if necessary. Thanks for the suggestion!
