### ISSUE TITLE
Modify various Rope iter-returning methods to use range arguments

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#571]
There are a number of methods implemented on `Rope` that return iterators. Currently these methods all take `start` and `end` arguments for specifying the range of the rope to iterate over. It would be more ergonomic if this could be a `Range` argument instead. For a guide, you can check out [`Vec::drain`](https://doc.rust-lang.org/1.24.1/src/alloc/vec.rs.html#1089) in the stdlib.

This will want to wait until #570 has been merged; part of this work can be removing the `_all` variants of these iterators that were added there.

This will also involve fixing various consumers of the existing API.

**Comment by LiHRaM** [comment]
I would like to give this a try. :)

**Comment by cmyr** [comment]
@LiHRaM You're totally welcome to take a stab at this; maybe what's easiest is to actually work off of my branch? if should get merged eventually. I can also open this PR from the main xi-editor repo, which would let you submit your PR onto that branch.

**Comment by LiHRaM** [comment]
@cmyr I've cloned your branch locally - is it okay if I just submit a PR against your branch there, or would you prefer if I submitted it against the main repo?
Personally, I don't care, but whatever's easiest for you. :)

**Comment by cmyr** [comment]
@LiHRaM I've moved that branch into this repo, you can PR to it here. (see #575)
