### ISSUE TITLE
Getting going with fuchsia and ledger

### ISSUE THREAD

**Issue by ghost** [xi-editor/xi-editor#641]
I want to get the rust crdt stuff going with the flutter / fuchsia frontend.

i read that the VIM2 board runs fuchsia. DO i need it ?

Where is a full setup for running it locally. I assume its qemu based ?

**Comment by gedw99** [comment]
I think that the rust core crdt can be used with both Flutter and Fuchsia.
WIth Flutter its just a plugin running through Method Channel. Have not gotten rust working this way yet but had no real issues doing it with golang.
If anyone has any links / tips please yell.

Regarding with Fuchsia, then i have to use FIDL, and not Method Channels ?

**Comment by Cogitri** [comment]
Closing since the original author is no more on GH
