### ISSUE TITLE
BaseMetric confusion

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#728]
I'm confused about `BaseMetric`, compared to `LinesMetric`.

Let's assume the rope contains `"$¢€💴"`. This is ten bytes, ten UTF-8 code units, and four unicode codepoints; 1, 2, 3, and 4 code units per codepoint, in order.

`s.measure::<BaseMetric>()` (which claims to return the number of boundaries) returns `10`; however if I make a cursor, and move through it with the `next()` fn, I will only find (including the starting `0`) four valid boundaries.

If I do the same with `LinesMetric`, I'll find that `measure()` returns the same result as I would get by manually counting with the `next` fn.

Is the behaviour of `BaseMetric` correct?

**Comment by raphlinus** [comment]
The confusion here is that the metric doesn't count the number of boundaries. Rather, it has a discontinuity at each boundary. In the case of `LinesMetric`, the step is 1, so these two concepts are the same. In the case of `BaseMetric`, the step is the number of utf-8 code units, hence the discrepancy.

Obviously we could have a `CodepointMetric` with a step of 1 at each codepoint. To _implement_ such a metric within the xi-rope framework would require a code point count in `RopeInfo`, which would have a small but nonzero cost.

**Comment by cmyr** [comment]
Sounds good. this is perhaps a docs issue then, unless I'm misunderstanding the first line of the docs here:

If you can think of an improvement I'll patch.

```rust
pub trait Metric<N: NodeInfo> {
    /// Return the number of boundaries in the NodeInfo::Leaf
    ///
    /// The usize argument is the total size/length of the node, in base units.
    fn measure(&N, usize) -> usize;
```

**Comment by raphlinus** [comment]
Yeah, that's wrong. Perhaps "Return the value for the NodeInfo::Leaf as measured by this metric."

There's some more cleanup that should happen here, which I think can be combined with the work to get rid of `Interval` and replace it by `Range<usize>` - that will simplify some of the concepts, and with that change I have more confidence it's really what I want it to be.
