### ISSUE TITLE
Web Browser (non-Electron) Client?

### ISSUE THREAD

**Issue by colemickens** [xi-editor/xi-editor#757]
Is anyone working on a web browser-based client for Xi?

One thing that appeals to me about (the planned features for) [xray](https://github.com/atom/xray) is that there is a client that runs fully in browser (if I understand correctly, part of the core runs in the browser vi wasm, but my understanding is that the browser client could run on a relatively low-powered device in order to work on a remote workspace, where language servers, debugging, etc can run in a more performant environment).

I'm curious if this is a scenario that would be feasible in Xi, or not. Particularly, I'm trying to understand if Xi and Xray are making different architectural decisions that would lend one or the other to be better suited for a "browser on a low-powered thin client" scenario? cc: @nathansobo

(Also, if there are any notes from the discussion(s) you two had about Xi and Xray, I'd be curious to understand the differences, at least given today's thinking.)

Thanks!

**Comment by cmyr** [comment]
We really haven't explored this at all, and it isn't in the immediate plans of anyone I'm in touch with, although I think it's been very casually mentioned before. I think that having a wasm core is a distinct issue from having remote editing sessions, which is definitely something we're interested in but also not thinking about too hard quite yet. :)

**Comment by nathansobo** [comment]
Yes, to confirm, one of our goals is to run completely in the browser.

**Comment by Cogitri** [comment]
Since this has been answered I'll close this. Feel free to re-open it if you need something else
