### ISSUE TITLE
Commands to increment and decrement numbers

### ISSUE THREAD

**Issue by portstrom** [xi-editor/xi-editor#807]
Vim has commands to [increment](https://vimhelp.appspot.com/usr_26.txt.html#26.2) (`Ctrl-A`) and decrement (`Ctrl-X`) numbers. These would be good to have in Xi as well.

Some details to pay attention to:
* If the caret is not pointing at a number, the next number after the caret is selected, but only within the same line.
* After the command, the caret is placed at the end of the number.
* Negative numbers are meaningfully handled.

**Comment by cmyr** [comment]
I'd put this firmly in 'one day'/'nice to have' territory? I do use this in vim sometimes, but it still feels like a slightly odd feature, that is mostly justified by it's use in macros? maybe?

Does it handle hex/octal/binary?

In any case, this does feel like a fun fairly self-contained project, so I would certainly be open to having someone work on it if they were interested.

**Comment by portstrom** [comment]
I don't use Vim often, and I don't even now how to make macros in Vim, but when I do use Vim, I often use this feature. When I use Emacs I miss it.

Octal numbers are handled in the confusing way you can see following the link. I think it would be better not to handle octal numbers, or have interpretation of numbers depend on the language being edited.

**Comment by terhechte** [comment]
I'd like to give this a try. If I manage to implement this, then I'll also add support to Xi-Mac

**Comment by terhechte** [comment]
I've added an implementation here: https://github.com/xi-editor/xi-editor/pull/877
