### ISSUE TITLE
Commands to move caret through undo history

### ISSUE THREAD

**Issue by portstrom** [xi-editor/xi-editor#808]
It would be helpful to have commands to place the caret at various changes in the undo history, without actually having to undo/redo the changes. I very often the caret around to look around the file, and then I want to move the caret back to where I was last editing. Sometimes I even want to walk through the undo history and see all the different places where I have recently edited something. I don't know of any other editor that has this feature.

**Specification:**

The commands “Move to previous change” (bound to `Alt-Z`) and “Move to next change” (bound to `Alt-Y`) select entries in the history of changes that can be undone and redone and place the caret at them.

When the last command used was not one of these commands, the command “Move to previous change” selects the latest change in the undo history before the start of the redo history, and the command “Move to next change” selects the earliest change in the redo history.

When the last command used was one of these commands, the command “Move to previous change” selects the latest change prior to the change selected by the last command, and the command “Move to next change” selects the earliest change after the change selected by the last command, aborting if there is no such entry.

The caret is placed at the end position of the selected change. The caret is transformed by applying the selected change and all intermediate changes until the current state of the document is reached. When the caret is within the range of a change to apply, the caret is placed at the end of that change.

**Comment by cmyr** [comment]
I like this idea; it's sort of like a more focused ctrl+o/ctrl+i (in vim).

Currently we don't stash selection state in the undo stack, which feels related, and would also be nice to have, e.g. undo should restore your selection/cursor state to whatever it was immediately before the current undo group was created.

**Comment by portstrom** [comment]
Using stashed selection state is a possibility, but even without it, just placing the caret at the end of the modified range of text is good enough.
