### ISSUE TITLE
Deserializing “find next” command fails on empty parameters

### ISSUE THREAD

**Issue by portstrom** [xi-editor/xi-editor#833]
The parameters of the “find next” command are all specified as optional. When they are all omitted, however, a custom deserializer for `EditCommand` [removes the parameters](https://github.com/xi-editor/xi-editor/blob/06f05b4e1e769f58156d87bab2d2c42e4cf2467b/rust/core-lib/src/rpc.rs#L524), causing deserialization to fail. **Suggested solution:** Simplify the protocol so all custom serializers and deseralizers can be removed.

**Comment by cmyr** [comment]
The RPC protocol predates our use of serde;  iirc the hack in question is what allows us to correctly deserialize `EditNotification` unit members. A rationalization of the protocol is definitely something we will want to consider at some point.

In the interim, the simplest solution may be to require any protocol method that takes params to have at least one non-optional param. An alternative solution could be to try deserializing first with params, and then only on failure try removing them.

**Comment by cmyr** [comment]
@scholtzan not sure if you saw this?
