### ISSUE TITLE
Send the position of all search matches to client

### ISSUE THREAD

**Issue by portstrom** [xi-editor/xi-editor#834]
I would like my client to display the position of all search matches in the scrollbar. Currently it seems like I can't, because Xi doesn't send the client any information about where the matches are. It only sends the number of matches and highlights those matches that are within the range of lines that are covered by the current scroll position. I would like Xi to send the client the line number of all matches. When the number of matches is too high to send the position of all matches without affecting the performance of the system, the positions can either not be sent at all, or the positions can be rounded to some interval and then duplicate positions removed.

**Comment by cmyr** [comment]
I think this is a reasonable feature request. sending line numbers should not be prohibitive, but we could have some maximum count we would return.

cc @scholtzan, you will have the best sense of this stuff..

**Comment by scholtzan** [comment]
I like the idea and it sounds definitely doable. I guess it needs a bit of planning and enhancing `find_status`.

**Comment by scholtzan** [comment]
Added in https://github.com/xi-editor/xi-editor/pull/928
