### ISSUE TITLE
Add a blog/updates section to the website?

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#835]
It would be nice to have an easy way of sharing updates/announcements. We _could_ have an 'updates'  repo/folder or something, and just commit markdown there, but it might make more sense to have just do it on the website? cc @ArazAbishov, not sure if you have any interest in this?

**Comment by ArazAbishov** [comment]
Yep, I can take a look into this depending on how fast it needs to be done :)

**Comment by cmyr** [comment]
no rush, but sometime in the next couple weeks would be nice?

**Comment by ArazAbishov** [comment]
Okay, I will try then :)

**Comment by ryanbloom** [comment]
The blog is now online at https://xi-editor.io/updates.html.
