### ISSUE TITLE
log file path should be specified by client

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#836]
logging setup currently fails on macOS for release builds because the application cannot write new files inside its app bundle. 

In any case, the expected location for logs is system dependent, and we should respect that. There may be a rust crate for finding log file paths, but we probably want the client to have ultimate control.

An alternative approach would be to build logging into the RPC process, such that all logs end up getting sent to the client, which can do with them what it wants; there are problems with this, though, such as how we would log errors in the RPC system itself. 😕

**Comment by 06kellyjac** [comment]
Looking into it 🙂

**Comment by cmyr** [comment]
@06kellyjac great! I _think_ the way that we will want to do this is by passing an argument to xi-core at exec time; we need to know the log path in `rust/src/main.rs`, so it can't happen later like with config paths.

We'd want this argument to be optional, so that clients that don't specify a log path still work fine. I'd also suggest just handling arg parsing manually for now, it's probably not worth bringing in a dependency yet. 😎

**Comment by 06kellyjac** [comment]
@cmyr I did a bit of digging before seeing your message so I went on a different route 😅. I found a crate that gets OS standard paths that can be the defaults (and I played around with it a bit); in this case for logs we'd want `XDG_DATA_DIRS` and other OS equivalents.

Technically there are two I looked at:

- <https://crates.io/crates/dirs>
- <https://crates.io/crates/directories>

They're both primarily by the same person and both up to date. I went with `dirs` as it looked quite nice to use and was more "low-level".

I'll get some of the code up soon for you to pick apart. I'm a bit new to Rust so any and all nitpicking is 100% welcome.

---

How do you want the argument to be passed in?

- `xi-editor --log-dir="SOMEPATH"`
- `LOG_DIR=log-dir="SOMEPATH" xi-editor`
- both?

Also for do you want `xi-core.log` & `xi-lsp-plugin.log` to go in the same directory?

I was thinking default to what's spat out of `dirs` & put both in there, then have `--log-dir` override that
(& then if you really wanted have a `--log-dir-lsp` to override the `xi-lsp-plugin.log` but maybe keep it to just `--log-dir` for now?)

Thanks 😄

**Comment by cmyr** [comment]
@06kellyjac I think we just one a single directory, and we'll put all log files there. `--log-dir` works. the `dirs` crate looks nice and light weight, so I'd go with that.

So: sounds good, basically!

the reason we want to pass in the logs dir is because xi-mac will want to use the log path associated with the main app bundle, at `Library/Logs/XiEditor`.

**Comment by 06kellyjac** [comment]
One PR ready for review/merge. Still WIP though; going to do the other parts in 2 more steps:

* [ ] Accept argument override `--log-dir` for `xi-core.log`
* [ ] Share new functionality with `xi-lsp-plugin.log`

**Comment by cmyr** [comment]
fixed in #888, thanks @06kellyjac!
