### ISSUE TITLE
Feature to move to a historic line number

### ISSUE THREAD

**Issue by portstrom** [xi-editor/xi-editor#848]
The use case is an IDE that can edit files and can also run a compiler and display the output from the compiler. When clicking a line number in the compiler output, the IDE shows the corresponding file and places the caret at that line number, adjusting the line number for any modifications that have been made to the file after the compiler was run. GNU Emacs already does this. This should be possible by having a counter of undo history entries that is copied at the time the compiler is run, and then giving Xi the counter when asking it to move to a line, and Xi will figure out how to transform the line number by inspecting the undo history.

**Comment by cmyr** [comment]
Something we would expect to support at some point in the future is the ability to display compiler output (warnings, errors) inline; some combination of error/warning marks in the gutter, and potentially annotations over the text itself, depending on what a given compiler provides. There's no API for this currently, but it's definitely in the queue. We also have a revision tracking system independent of undo state that would make it fairly trivial to correctly provide this information in light of subsequent edits.

Does that mostly provide what you're talking about?

**Comment by portstrom** [comment]
Displaying annotations based on compiler output directly in the file would be helpful in addition to the feature I described. These two features might overlap so much in implementation it may be good to implement them together.
