### ISSUE TITLE
Use more structured RPC commands for motion, deletion, scrolling, etc a la Vim operators

### ISSUE THREAD

**Issue by bch29** [xi-editor/xi-editor#86]
Right now, the RPC commands include things like

```
move_up
move_down
move_left
move_right
move_to_end_of_line
move_to_left_end_of_line
...
delete_forward
delete_backward
delete_to_end_of_paragraph
delete_to_beginning_of_line
...
```

I'm proposing to factor commands like these into simple "move" and "delete" commands, which also take an argument indicating where to move/delete/scroll to. These would be objects like

```
up_line
down_line
left_char
right_char
left_word
right_word
end_of_paragraph
beginning_of_paragraph
...
```

This should reduce the explosion of edit commands significantly, and also simplify the implementation of Vim-like keys, among other things.

**Comment by bch29** [comment]
I've made a start at implementing this on my [`develop` branch](https://github.com/bch29/xi-editor/tree/develop). It works with [my fork of `xi_glium`](https://github.com/bch29/xi_glium).

**Comment by hh9527** [comment]
i like this idea, and maybe an additional field "repeat" with these actions is even better?

**Comment by robert-snakard** [comment]
would it be possible to define a text-object type? `down_line`, `right_word`, and `end_of_paragraph` are both changed to a `next` rpc command with text-objects line, word, and paragraph respectively.

**Comment by Cogitri** [comment]
Heya, is this still desirable?

**Comment by cmyr** [comment]
happy to close for now, we've made lots of movement in this direction.
