### ISSUE TITLE
allow client to override a buffer's language

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#866]
This requires a new top-level RPC, which we might call `set_language`, which passes a `ViewId` and a `LanguageId`. When handling in `tabs.rs`, we'll need to call `config_manager.override_language(..)`.

I'm not sure if this is the approach we'll want to take long term, but I think it's a reasonable at this point and it isn't hard to change later.

Won't be useful until #863 is also finished, and should probably be implemented alongside a `xi-mac` PR for easy testing.

**Comment by mrandri19** [comment]
I've started working on it
