### ISSUE TITLE
Deleting references to Google license

### ISSUE THREAD

**Issue by theptrk** [xi-editor/xi-editor#867]
The main `README.md` still refers to the Google license meaning Google ownership over this project. This news report `https://9to5google.com/2018/10/02/xi-code-editor-no-longer-google-project/` says that this project is now open source. 

We should delete the references to the Google license on the main page so readers aren't driven away.

**Comment by cmyr** [comment]
The project has always been open source, but yes contributors are no longer expected to sign the Google CLA. This change would be welcome. Thanks for the issue!

**Comment by jansol** [comment]
I've actually been meaning to do this. Will get to it later today unless someone beats me to it.

**Comment by unmellow** [comment]
i made that change but it won't let me push so here https://mega.nz/#!Bo5lyK6R!U2WQqR_pb0OABXiUVy_HvWMCszrRcAT-58EAgkt_0ZA

**Comment by theptrk** [comment]
Thanks!
