### ISSUE TITLE
Commands to treat underscores as word boundary

### ISSUE THREAD

**Issue by portstrom** [xi-editor/xi-editor#874]
Emacs treats underscores as word boundaries when moving or deleting one word forwards or backwards. Atom can optionally treat underscores as a word boundary by holding either Alt or Ctrl. Xi currently never treats underscores as a word boundary. I think it would make sense for Xi to do like Atom and offer both variants, and the frontend can decide which one to use. Personally I would always have it work like in Emacs. I often need to change one word within an identifier, and it's annoying when commands that act on words run past any underscores.

**Comment by cmyr** [comment]
Yea, more granularity in movement commands is something currently being discussed in #826.

I could definitely imagine a 'big word'/'small word' distinction, that would account for underscores, camelcase, brackets, etc; 'big word' would just look for the next space. Sublime has a reasonable approach to this, where the set of 'word dividing characters' is a per-language setting.
