### ISSUE TITLE
Remove Interval data structure

### ISSUE THREAD

**Issue by raphlinus** [xi-editor/xi-editor#914]
The xi-editor codebase is complex. Some of the complexity is in service of important goals, for example the asynchronous design is in service of greater responsiveness and not blocking user input. Other sources of complexity are not pulling their weight. I think the best example of that is the `Interval` datatype. This issue contains a plan to remove it.

## Original motivation

The notion of "interval" is tied to metrics and, in particular, boundaries. It was also intended to capture subtle behavior about editing. For example, when inserting a character at the beginning or end of a span, does the span extend to the inserted character, or is the character inserted outside it? A large part of the idea of "interval" was to specify the various choices, and was directly inspired by the [SPAN_INCLUSIVE_EXCLUSIVE](https://stackoverflow.com/questions/9879233/explain-the-meaning-of-span-flags-like-span-exclusive-exclusive) mechanism in Android. The idea was that the desired behavior would naturally fall out of algebra between points and spans. That idea has not been realized.

Also, there was a vague inspiration (from the CRDT literature) that positions in a string as it's being edited correspond to real numbers. Thus, "after 2" and "before 3" might be different locations after an insert at 3, even though they're the same cursor position before. This idea also never really materialized, and instead we should use "priorities," which I think are still a good idea.

Lastly, when expressing intervals in terms of lines rather than bytes, I wanted to use an interval closed at the end to represent the partial line at the end.

I'll use the standard notation (same as [Wikipedia](https://en.wikipedia.org/wiki/Interval_(mathematics))) here. [0, 1) is a closed-open interval, (1, 2) is open-open, (2, 3] is open-closed, and [3, 4] is closed-closed.

## The plan

The plan, in brief, is to find all occurrences of intervals which are not closed-open, and reimplement the underlying logic to use closed-open intervals instead. Once all uses of intervals are closed-open, they can be replaced with a more idiomatic `Range` instead (see #576 for some of the existing work in using `Range`).

Doing a simple `git grep Interval::new | grep -v "closed_open"` search, I see a number of uses, though most seem to be tests. My gut feeling is that most can be changed straightforwardly, but breaks will require a re-think.

## Breaks

The concept of boundaries or breaks pervades xi-editor. The newlines in strings are considered "hard breaks," and the fundamental rope representation for strings contains data to facilitate fast seeking. In addition, to implement word wrapping, there is a [`Breaks`](https://github.com/xi-editor/xi-editor/blob/master/rust/rope/src/breaks.rs) data structure, which contains additional breaks from wrapping. At the moment, the breaks data structure contains both hard breaks and soft breaks, but to make async line wrapping more efficient, there is a plan to change it to soft breaks only, so to find _all_ breaks, it will be necessary to merge the two (see #610). However, that's out of the scope of this issue (just included for context).

Take as a running example the string `"abc def\nghi"`. This string has a line boundary at offset 8. Byte 7 is a newline character.

Currently, the breaks data structure is conceptually a set of break positions, and is represented as a list of those positions, chunked up into a rope-like structure. So for this string, the list would be [8]. However, consider what needs to be done to keep this structure up to date when the underlying string is edited. If the newline at 7 is deleted, ie the closed-open interval [7, 8) is deleted, then the newline at 8 is also to be deleted. In the existing framework, that's respresented by changing the closed-open interval to an open-closed interval (7, 8], and deleting that.

This logic is confusing, even to me, and the word wrap logic is still not completely correct after several attempts to fix it. After wrestling with it a while, I think I have an easier approach.

The new approach is to treat the breaks data structure as a sequence of bits, false representing no break, and true representing a break immediately _after_ that position. Thus, to find the hard breaks, just compare each byte in the string with newline.

Thus, to delete [7, 8) in the string, you also delete [7, 8) in the breaks data structure.

To represent a soft break, the bit is set at the _last_ code unit in the unicode codepoint immediately preceding the break. Thus, the break is always immediately after the true bit, and boundaries can be found without reference to the underlying string. This was a subtlety I didn't get at first.

Implementation-wise, the main difference should be storing one less than the current value in the breaks leaf data structure. I think the builder external interface can remain the same (thus, it subtracts 1 from its argument before storing), and the location of boundaries should also remain the same (thus, they add one before returning a boundary). The substring logic of course will change, which requires the corresponding logic in all uses of substring (of which editing is probably the most important).

The incremental editing logic for word wrap (at the end of [linewrap.rs](https://github.com/xi-editor/xi-editor/blob/master/rust/core-lib/src/linewrap.rs)) will require a fair amount of rework, but it needs it in any case, it's not correct. It would also be great to write tests exercising the fact that the results are the same after incremental edits as doing a batch rewrap of the entire string.

**Comment by cmyr** [comment]
Playing around more with this,  I think it makes sense to leave the (newly simplified) interval type in place, for the following reasons:

- we can't impl Debug/Display on `Range<usize>`
- `Range<usize>` isn't `Copy`
- we can't have a fn `is_empty` in a trait, without getting a warning, because it may be added to the stdlib at some point;
- By implementing `From<Range<usize>> for Interval`, `From<RangeInclusive> for Interval` etc, we can still use range syntax where appropriate by changing fn signatures to take a T: Into<Interval>.
- `Range` implements `Iterator`, and this is one of it's major use cases; we might not want this behaviour.

Ultimately the main problem with interval is its complexity; the fact that we have a type at all isn't a big problem, so I think leaving it in is worth it given these issues.

**Comment by cmyr** [comment]
resolved in #941
