### ISSUE TITLE
Atomic save

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#918]
Inspired by #913, here's another 'don't lose user data' feature:

Currently, we save files in place. This is potentially dangerous; if there is a panic or a power failure while we're overwriting a file, we risk destroying user data.

What most editors do is to write the file first to a temporary path, and then move this file to the final path with `mv` or similar. You could also copy the original file to a backup location, and then overwrite the original. For more information, here's a SO question: [how does vim save files?](https://stackoverflow.com/questions/13563627/how-does-vim-save-files)

**Comment by mbStavola** [comment]
I'd like to take this!

**Comment by cmyr** [comment]
@mbStavola sounds good! I was talking to someone on IRC the other day who had expressed interest in this issue, so I'll try and check in with them and see how concrete that interest was; you should feel free to start figuring out the approach you'd take and if they get back to me with strong feelings I'll let you know. 😎

**Comment by mbStavola** [comment]
Awesome, I'll definitely drop by the IRC at some point. Never used zulip before, but it looks pretty sweet!
