### ISSUE TITLE
VIM for XI ?

### ISSUE THREAD

**Issue by Byron** [xi-editor/xi-editor#93]
This issue is merely a question. If it's a bad place to put it here, please let me know where to direct it otherwise. That said: **Do you think it's feasible to implement VIM-like command support in a way that allows it to be re-used by all frontends ?**

To me, without nearly no knowledge about the XI architecture, it seems like it should be a command-handler running in the backend. Front-ends would need some sort of connector to send all key-presses to it, and it would decide on what to do. Effects of its operation could either manifest themselves in changes to the document itself, or the GUI. The latter would happen during mode-changes for example.

The second question coming to my mind: **Would it be feasible to start with the backend VIM plugin already ?**

_(My motivation to become more active with this is the promise of having a next-gen editor, which from the very beginning is build around high-performance data structures and programming languages. Right now, both Atom and IntelliJ seem to lag even with small files, and during ordinary interactions.)_

**Comment by porglezomp** [comment]
I'm wondering if there should maybe be one more layer. I haven't really contributed to the project, but every time I come by I see some people discussing sticking common interaction code into the core. How well would it work to have

- Frontend: Platform specific, native interactions, sends events down the chain
- Middle: Interaction specific, one for modal editing and one for single-mode editing
- Backend: Performs the editing operations, just like now

The downsides I can immediately see here are the obvious complexity one, and the obvious performance one (which could maybe be reduced by having a channel between 1 and 3 for all the purely presentational issues). Has an architecture like this been suggested before?

**Comment by emoon** [comment]
Bump. I would like to hear more thoughts on this.

**Comment by cmyr** [comment]
This is something we would like to get around to eventually, but an earlier priority is fleshing out more of the basic editor functionality.

**Comment by emoon** [comment]
Sounds good. Thanks for the reply.

**Comment by dotancohen** [comment]
+1 support for a VIM mode. Xi is the first editor that I've been excited about in over a decade, but without a VIM mode it would be useless to me.

**Comment by dayuoba** [comment]
how i wonder such cool editor with vim mode!

**Comment by autoferrit** [comment]
One thing that would be awesome, is to have an easy keymap structure like space-neovim, spacemacs, and others. I would still prefer vim bindings, but this adds essentially a UI layer over the keybinding to make them easier to discover and remember as well. which is the big thing for me (using space-neovim).

**Comment by dineshbhosale** [comment]
Spacemacs keybindings are <3

**Comment by dineshbhosale** [comment]
For adding some substance , to above comment 
Please take a look at agronomic keybindings of spacemacs and why so many people are requesting a vim mode for XI editor.

http://spacemacs.org/doc/DOCUMENTATION.html#evil-plugins

**Comment by jansol** [comment]
Closing in favor of #302
