### ISSUE TITLE
Add zulip info to readme / contributing.md, tell everyone to join zulip

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#961]
We're testing out using zulip for discussion and coordinate; signup is open to anyone with a github account at https://xi.zulipchat.com.

**Comment by portstrom** [comment]
It doesn't seem to work. I just get to “Find your Zulip accounts…”.

**Comment by portstrom** [comment]
@LiHRaM First I get a short description of Xi and “Log in with Github”. When authenticated with Github I get “Find your Zulip accounts” and “We will send you an email with the sign-in information for any Zulip organization(s) associated with the addresses you enter below.” and no other option than to enter email addresses to find accounts.

**Comment by raphlinus** [comment]
@portstrom I can try sending you an invite if that would help. Otherwise I'm not sure what's going on. You can also ask support@zulipchat.com.

**Comment by cmyr** [comment]
@portstrom I remember being confused as well by some step that was pre-loaded with my email; it's the email associated with your github account, but that isn't necessarily obvious? In any case it took me a bit of clicking around, not sure if you're having the same problem?

**Comment by portstrom** [comment]
Now I tried the address associated with my Github account and got nothing. Why not try another chat service that works?

**Comment by LiHRaM** [comment]
> @LiHRaM First I get a short description of Xi and “Log in with Github”. When authenticated with Github I get “Find your Zulip accounts” and “We will send you an email with the sign-in information for any Zulip organization(s) associated with the addresses you enter below.” and no other option than to enter email addresses to find accounts.

Could you share a screenshot of this screen? I feel like there's something I'm missing...

**Comment by portstrom** [comment]
@LiHRaM
![zulip](https://user-images.githubusercontent.com/23269669/47908727-1ee75700-de8e-11e8-9d5d-068a391b3e49.png)

**Comment by LiHRaM** [comment]
This is different from the screen that I saw - I had an option to register my account, and did so. Maybe you could try contacting them?

**Comment by portstrom** [comment]
That screen that shows after authenticating with Github has the URL `https://auth.zulipchat.com/accounts/find/`.

**Comment by cmyr** [comment]
@portstrom send an email to first.last@gmail.com (with the name in my github profile) and I'll send you an invite? Maybe that will be easier?

I'd also maybe try another browser or an incognito window or something in case there's something weird going on? It's working for ~40 other people so far with no complaints.

**Comment by portstrom** [comment]
I changed the primary email address for my Github account and removed the other address. Then I didn't get the “Find your Zulip accounts” screen, but another screen that let me register without problems.
