### ISSUE TITLE
fix xi-trace clippy lints

### ISSUE THREAD

**Issue by cmyr** [xi-editor/xi-editor#992]
xi-trace is currently failing the clippy section of CI on windows. See [this job](https://travis-ci.com/xi-editor/xi-editor/jobs/159153709) for an example.

This should be as simple as making the changes suggested in the link above, and making sure that clippy passes on windows.

**Comment by ThisisGurwinder** [comment]
@cmyr I am new to rust language and want to contribute.
Can I try my luck with this?

**Comment by jansol** [comment]
Sure, go ahead. Feel free to ask if any questions arise.

**Comment by ThisisGurwinder** [comment]
Can we fix this issue with following PR?

https://github.com/xi-editor/xi-editor/pull/997
